"""Render formal leadership templates with native challenger admission closed.

External probes retain their own generator. Formal output never opts into an
unverified native challenger registration or contains an acceptance fixture.
"""
from __future__ import annotations

import argparse
from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[1]
SOURCE = Path(__file__).resolve().parent / "leadership_templates"


def build_outputs() -> dict[str, bytes]:
    outputs = {}
    for source in sorted(SOURCE.rglob("*.in")):
        relative = source.relative_to(SOURCE).with_suffix("").as_posix()
        text = source.read_text(encoding="utf-8-sig").replace("@NATIVE_CHALLENGER_PROBE@", "no")
        if re.search(r"@[A-Z_]+@", text):
            raise ValueError(f"Unrendered leadership token: {relative}")
        lines = text.splitlines()
        comment = "# GENERATED FILE: edit tools/leadership_templates and run tools/gen_runtime.py."
        if relative.startswith("localization/"):
            lines.insert(1, " " + comment)
        else:
            lines.insert(0, comment)
        outputs[relative] = ("\n".join(line.rstrip() for line in lines) + "\n").encode("utf-8-sig")
    if len(outputs) != 12:
        raise ValueError("Leadership template inventory must contain exactly 12 runtime files")
    return outputs


def generate(output: Path = ROOT, *, check: bool = False) -> list[str]:
    mismatches = []
    for relative, payload in build_outputs().items():
        target = output / relative
        if check:
            if not target.is_file() or target.read_bytes() != payload:
                mismatches.append(relative)
        else:
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_bytes(payload)
    return mismatches


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path, default=ROOT)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    mismatches = generate(args.output, check=args.check)
    if mismatches:
        print("Leadership generated bytes differ: " + ", ".join(mismatches))
        return 1
    print("Leadership templates verified" if args.check else "Leadership templates generated")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
