"""Append one exact external candidate index; no game, Git mutation, or inputs."""

from datetime import datetime, timezone
import hashlib
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
PARENT = ROOT.parent / "iteration2-admitted-candidate-001"
NATIVE = Path("C:/Program Files (x86)/Steam/steamapps/common/Crusader Kings III/game")


def digest(path):
    return hashlib.sha256(path.read_bytes()).hexdigest()


def write_new(path, data):
    if path.exists():
        raise ValueError(f"Append-only target already exists: {path}")
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(data, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")


def main():
    manifest = json.loads((ROOT / "evidence/nonce-parent-input-manifest.json").read_text(encoding="utf-8"))
    changed = [name for name, expected in manifest["files"].items()
               if not (PARENT / name).is_file() or digest(PARENT / name) != expected]
    current_parent_files = {path.relative_to(PARENT).as_posix()
                            for path in PARENT.rglob("*") if path.is_file()}
    added_parent_files = sorted(current_parent_files - set(manifest["files"]))
    if changed or added_parent_files:
        raise ValueError(f"Parent candidate changed: {changed}; added={added_parent_files}")
    latest = ROOT / "evidence/offline-20261004T075815354477Z/offline-report.json"
    offline = json.loads(latest.read_text(encoding="utf-8"))
    if (offline["result"] != "PASS_OFFLINE" or offline["test_exit_code"] != 0
            or offline["check"]["mismatches"] or not offline["checkout_unchanged"]):
        raise ValueError("Required affected offline proof did not pass")
    for name, expected in offline["authored_source_sha256"].items():
        if digest(ROOT / name) != expected:
            raise ValueError(f"Tested authored input changed: {name}")
    for name, expected in offline["render"]["files"].items():
        if digest(ROOT / "generated/mod_li_yu_dao" / name) != expected:
            raise ValueError(f"Tested generated bytes changed: {name}")
    launcher = NATIVE.parent / "launcher/launcher-settings.json"
    settings = json.loads(launcher.read_text(encoding="utf-8-sig"))
    keys = ["common/scripted_effects/pam_heresy_shared_effects.txt",
            "common/scripted_effects/pam_effects.txt",
            "common/scripted_effects/00_religion_effects.txt",
            "common/religion/rite_types/_rite_types.info"]
    native = {"schema": "lyd.c2.nonce-native-gap-review.v1",
              "source_root": NATIVE.as_posix(), "launcher_path": launcher.as_posix(),
              "launcher_sha256": digest(launcher), "launcher_version": settings.get("version"),
              "launcher_raw_version": settings.get("rawVersion"),
              "files": {name: digest(NATIVE / name) for name in keys},
              "text_search": {"argv": ["rg", "-n", "has_same_core_doctrines|has_same_core_tenets|same_core_tenet", NATIVE.as_posix()],
                              "observed_exit_code": 1, "observed_stdout": "", "observed_stderr": "",
                              "boundary": "Previously completed local text search; no matching text is not proof of missing engine API."},
              "doctrine_iterator": {"source": "common/scripted_effects/pam_heresy_shared_effects.txt:50-65",
                                    "boundary": "Original use is HoR-known rite doctrines; non-HoR representative completeness needs cold verification."},
              "exe_read": False, "live": "NOT_RUN"}
    write_new(ROOT / "evidence/nonce-native-source-boundary.json", native)
    delta = []
    for folder in ("source", "tools", "generated", "docs"):
        for path in sorted((ROOT / folder).rglob("*")):
            if path.is_file():
                name = path.relative_to(ROOT).as_posix()
                actual = digest(path)
                old = manifest["files"].get(name)
                if old != actual:
                    delta.append({"path": name, "sha256": actual, "parent_sha256": old})
    report = {"schema": "lyd.c2.nonce-repair-candidate.v1", "utc": datetime.now(timezone.utc).isoformat(),
              "nonce_repair": "PASS_OFFLINE_ONLY", "tests": 85, "original_tests": 65,
              "new_tests": 20, "generated_files": 15, "live": "NOT_RUN",
              "runtime_admission": "R0002_NATIVE_PRIMITIVES_ONLY_NOT_NEW_CONSENT_OR_HEAD_FLOW",
              "parent_candidate_unchanged": True, "parent_input_files": len(manifest["files"]),
              "parent_input_manifest": "evidence/nonce-parent-input-manifest.json",
              "offline_report": latest.relative_to(ROOT).as_posix(), "offline_report_sha256": digest(latest),
              "offline_checkout": offline["checkout_before"]["head"],
              "prior_nonce_attempt": {"path": "evidence/offline-20261004T075141184664Z/offline-report.json",
                                      "tests_passed": 83, "result": "FAIL_OFFLINE",
                                      "reason": "Existing root-owned tracked changes rejected the clean-checkout guard; historical report preserved."},
              "nonce_guards": ["saved_actor", "saved_moving_rite", "rite_serial", "terms_revision", "persistent_actor_callback_nonce", "vote_nonce", "player_nonce"],
              "entry_ids_unchanged": True, "shared_c3_dependencies_unchanged": True,
              "open_release_blocker": "Consent electorate excludes landless human players; all-affected-player contract needs separate scope correction.",
              "not_proven": offline["not_proven"], "no_zero_error_log_green": True, "delta": delta}
    write_new(ROOT / "candidate-report.json", report)
    files = {path.relative_to(ROOT).as_posix(): {"sha256": digest(path), "bytes": path.stat().st_size}
             for path in sorted(ROOT.rglob("*")) if path.is_file() and path.name != "candidate-index.json"}
    write_new(ROOT / "candidate-index.json", {"schema": "lyd.c2.nonce-candidate-index.v1",
              "candidate_report": "candidate-report.json", "files": files})
    print(json.dumps({"report": str(ROOT / "candidate-report.json"),
                      "report_sha256": digest(ROOT / "candidate-report.json"),
                      "index": str(ROOT / "candidate-index.json"),
                      "index_sha256": digest(ROOT / "candidate-index.json")}, indent=2))


if __name__ == "__main__":
    main()
