"""Build a separate development overlay; never register, launch or touch production."""
from __future__ import annotations

import argparse
import difflib
import hashlib
import json
from pathlib import Path
import re
import textwrap

NAMESPACE = 'lyd_factory_diag'
NAME = 'LYD Factory Operation Diagnostic - DEVELOPMENT ONLY'
PINS = {
    'common/scripted_effects/lyd_c3_head_factory.txt': 'bf1b40de272467afd9b1e0eb2e3c59c4f62285d0daef314cb066446467efccc7',
    'common/scripted_effects/lyd_i3b_commit_effects.txt': 'deb4229267593e88f3ed21a8b1b4611ae2e30f9ad6e3ee18d4119f37e58362ec',
}


def digest(raw):
    return hashlib.sha256(raw).hexdigest()


def file_ref(path):
    raw = path.read_bytes()
    return {'path': path.as_posix(), 'bytes': len(raw), 'sha256': digest(raw)}


def lines(text, first, last):
    return textwrap.dedent('\n'.join(text.splitlines()[first - 1:last])) + '\n'


def indent(text, spaces=4):
    return textwrap.indent(text.rstrip() + '\n', ' ' * spaces)


def effect(name, body):
    return name + ' = {\n' + indent(body) + '}\n'


def transition(stage):
    return f'save_scope_value_as = {{ name = lyd_factory_diag_stage value = {stage} }}\ntrigger_event = {NAMESPACE}.{stage}\n'


def generate(factory, commit, product_name):
    preamble = lines(commit, 18, 29)
    initial_guard = lines(commit, 12, 16)
    factory_guard = lines(factory, 7, 14)
    capture = lines(factory, 16, 22)
    finish = lines(commit, 31, 66)
    early_failure = lines(factory, 56, 56)
    failure_log = 'debug_log = "LYD_C3_HEAD_FACTORY_REJECTED"\n'
    # The existing reject path continues original postconditions; no false stage.
    opening = 'if = {\n' + indent('limit = {\n' + indent(initial_guard) + '}\n')
    opening += indent(preamble)
    opening += indent('if = {\n' + indent('limit = {\n' + indent(factory_guard) + '}\n' + capture + transition(1)) + '}\n')
    opening += indent('else = {\n' + indent(failure_log + finish + 'lyd_i3b_show_result_effect = yes\n') + '}\n')
    opening += '}\n'
    text = '# DEVELOPMENT ONLY overlay. Generated by build_diagnostic_overlay.py; production is untouched.\n'
    text += lines(commit, 3, 9) + '\n'
    text += effect('lyd_i3b_commit_effect', opening) + '\n'
    text += lines(commit, 70, 78) + '\n'
    chunks = {
        2: lines(factory, 23, 36),
        3: lines(factory, 37, 37),
        4: lines(factory, 38, 50),
        5: lines(factory, 51, 51),
        6: lines(factory, 52, 54) + finish,
    }
    for stage, chunk in chunks.items():
        text += effect(f'lyd_factory_diag_d{stage}_effect', chunk + transition(stage)) + '\n'
    trigger = '''# DEVELOPMENT ONLY: continuation identity, not a new mandate.
lyd_factory_diag_continue_trigger = {
    lyd_i3b_cancel_context_trigger = yes
    has_variable = lyd_c3_head_creation_authorized
    exists = scope:lyd_c3_factory_faith
    faith = scope:lyd_c3_factory_faith
    faith = var:lyd_i3b_faith
    rite = var:lyd_i3b_main
    exists = scope:lyd_factory_diag_stage
    scope:lyd_factory_diag_stage = $STAGE$
}
lyd_factory_diag_title_trigger = {
    exists = scope:new_title
    scope:new_title = {
        holder = root
        var:lyd_c2_owned_head_title = 1
        var:lyd_c2_owner_faith = scope:lyd_c3_factory_faith
    }
}
lyd_factory_diag_result_trigger = {
    lyd_i3b_result_actor_trigger = yes
    exists = scope:lyd_i3b_actor
    this = scope:lyd_i3b_actor
    var:lyd_i3b_result_serial = scope:lyd_i3b_event_serial
    var:lyd_i3b_result_nonce = scope:lyd_i3b_event_nonce
    exists = scope:lyd_factory_diag_stage
    scope:lyd_factory_diag_stage = 6
}
'''
    events = '# DEVELOPMENT ONLY: no immediate mutators, no timed continuation.\nnamespace = ' + NAMESPACE + '\n\n'
    for stage in range(1, 7):
        if stage == 6:
            guard = 'lyd_factory_diag_result_trigger = yes\n'
            operation = 'lyd_i3b_show_result_effect = yes\n'
        else:
            guard = f'lyd_factory_diag_continue_trigger = {{ STAGE = {stage} }}\n'
            if stage == 1:
                # Reuse the actual original factory limit before title creation.
                guard += factory_guard
            else:
                guard += 'lyd_factory_diag_title_trigger = yes\n'
            if stage >= 3:
                guard += 'faith.religious_head_title = scope:new_title\n'
            operation = f'lyd_factory_diag_d{stage + 1}_effect = yes\n'
        events += f'{NAMESPACE}.{stage} = {{\n'
        events += '    type = character_event\n    theme = faith\n'
        events += f'    title = lyd_factory_diag_d{stage}_title\n    desc = lyd_factory_diag_d{stage}_desc\n'
        events += '    trigger = {\n' + indent(guard, 8) + '    }\n'
        events += '    option = {\n        name = lyd_factory_diag_next\n'
        events += '        trigger = {\n' + indent(guard, 12) + '        }\n'
        events += '        hidden_effect = {\n            if = {\n                limit = {\n' + indent(guard, 20) + '                }\n'
        events += indent(operation, 16) + '            }\n        }\n    }\n}\n\n'
    descriptor = f'version="0.0.1"\nname={json.dumps(NAME)}\nsupported_version="1.20.*"\ndependencies={{ {json.dumps(product_name, ensure_ascii=False)} }}\n'
    cn = ['D1：doctrine 与合法授权后', 'D2：create / holder / resolve 后', 'D3：SetHoF 后', 'D4：原条件 cleanup 后', 'D5：COA / Title95 后', 'D6：原 postconditions 与 close 后']
    en = ['D1: doctrine and lawful authorization', 'D2: create / holder / resolve', 'D3: SetHoF', 'D4: original conditional cleanup', 'D5: COA / Title95', 'D6: original postconditions and close']
    locales = {}
    for language, titles in (('english', en), ('simp_chinese', cn)):
        rows = [f'l_{language}:']
        for number, title in enumerate(titles, 1):
            rows.append(f' lyd_factory_diag_d{number}_title:0 "{title}"')
            desc = 'DEVELOPMENT DIAGNOSTIC ONLY. Observe cache and save before advancing; this does not prove political protection.' if language == 'english' else '仅开发诊断。推进前读取缓存并保存；本页不证明政治保护通过。'
            rows.append(f' lyd_factory_diag_d{number}_desc:0 "{desc}"')
        caption = 'Advance one diagnostic boundary' if language == 'english' else '仅推进下一个诊断边界'
        rows.append(f' lyd_factory_diag_next:0 "{caption}"')
        locales[f'localization/{language}/lyd_factory_operation_diagnostic_l_{language}.yml'] = '\n'.join(rows) + '\n'
    return {
        'descriptor.mod': descriptor,
        'common/scripted_effects/lyd_i3b_commit_effects.txt': text,
        'common/scripted_triggers/lyd_factory_operation_diagnostic.txt': trigger,
        'events/lyd_factory_operation_diagnostic.txt': events,
        **locales,
    }


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--source-root', required=True)
    parser.add_argument('--source-head', required=True)
    parser.add_argument('--export-report', required=True)
    parser.add_argument('--export-report-sha256', required=True)
    parser.add_argument('--output', required=True)
    args = parser.parse_args()
    source = Path(args.source_root).resolve()
    output = Path(args.output).resolve()
    report_path = Path(args.export_report).resolve()
    report_raw = report_path.read_bytes()
    if digest(report_raw) != args.export_report_sha256:
        raise ValueError('Actual export REPORT SHA mismatch')
    report = json.loads(report_raw)
    if re.fullmatch('[0-9a-f]{40}', args.source_head) is None:
        raise ValueError('Require explicit actual full source HEAD')
    if report['source']['head'] != args.source_head or Path(report['source_root']).resolve() != source:
        raise ValueError('Actual export HEAD/root binding mismatch')
    if output.exists():
        raise FileExistsError(output)
    mod = source / 'mod_li_yu_dao'
    input_refs = []
    texts = {}
    for relative, expected in PINS.items():
        path = mod / relative
        raw = path.read_bytes()
        if digest(raw) != expected:
            raise ValueError(f'Production preimage changed: {relative}')
        input_refs.append(file_ref(path))
        texts[relative] = raw.decode('utf-8-sig')
    factory = texts['common/scripted_effects/lyd_c3_head_factory.txt']
    commit = texts['common/scripted_effects/lyd_i3b_commit_effects.txt']
    descriptor = (mod / 'descriptor.mod').read_text(encoding='utf-8-sig')
    product_name = re.search(r'^name="([^"]+)"', descriptor, re.M).group(1)
    files = generate(factory, commit, product_name)
    output.mkdir(parents=True)
    rows = []
    for relative, text in files.items():
        path = output / relative
        path.parent.mkdir(parents=True, exist_ok=True)
        encoding = 'utf-8-sig' if path.suffix == '.yml' else 'utf-8'
        with path.open('x', encoding=encoding, newline='\n') as stream:
            stream.write(text)
        rows.append({'relative_path': relative, **file_ref(path)})
    patch = ''.join(difflib.unified_diff(commit.splitlines(keepends=True), files['common/scripted_effects/lyd_i3b_commit_effects.txt'].splitlines(keepends=True), fromfile='production/common/scripted_effects/lyd_i3b_commit_effects.txt', tofile='diagnostic/common/scripted_effects/lyd_i3b_commit_effects.txt'))
    patch_path = output.parent / (output.name + '.commit-override.patch')
    with patch_path.open('x', encoding='utf-8', newline='\n') as stream:
        stream.write(patch)
    receipt = {
        'schema': 'lyd.factory-operation-diagnostic-overlay.v1',
        'status': 'FILE_ONLY_CANDIDATE_NOT_REGISTERED_OR_LAUNCHED',
        'actual_source_head': args.source_head,
        'actual_export_report': file_ref(report_path),
        'original_production_source_inputs': input_refs,
        'mod_name': NAME,
        'load_after_product_name': product_name,
        'files': rows,
        'production71_modified': False,
        'main_writes': 0,
        'runtime_acceptance': None,
        'diagnostic_business_credit': None,
        'whole_mod': 'NOT_GREEN',
        'patch': file_ref(patch_path),
        'stage_keys': [f'{NAMESPACE}.{stage}' for stage in range(1, 7)],
        'stage_scope': 'lyd_factory_diag_stage',
        'D6': 'Original bookkeeping/postconditions/close completed; only after observing D6 does its option call the original show_result_effect.',
    }
    manifest_path = output.parent / (output.name + '.MANIFEST.json')
    with manifest_path.open('x', encoding='utf-8', newline='\n') as stream:
        json.dump(receipt, stream, ensure_ascii=False, indent=2)
        stream.write('\n')
    print(json.dumps({'manifest': file_ref(manifest_path), 'file_count': len(rows), 'runtime_acceptance': None}, ensure_ascii=True))


if __name__ == '__main__':
    main()
