"""Build a separate development overlay; never register, launch or touch production."""
from __future__ import annotations

import argparse
import difflib
import hashlib
import json
from pathlib import Path
import re
import textwrap

NAMESPACE = 'lyd_factory_diag'
STAGE_ORDER = (1, 20, 2, 3, 4, 5, 6)
NAME = 'LYD Factory Operation Diagnostic - DEVELOPMENT ONLY'
TRANSACTION_MARKER = 'lyd_factory_diag_empty_transaction_completed'
PINS = {
    'common/scripted_effects/lyd_c3_head_factory.txt': 'bf1b40de272467afd9b1e0eb2e3c59c4f62285d0daef314cb066446467efccc7',
    'common/scripted_effects/lyd_i3b_commit_effects.txt': 'deb4229267593e88f3ed21a8b1b4611ae2e30f9ad6e3ee18d4119f37e58362ec',
}


def digest(raw):
    return hashlib.sha256(raw).hexdigest()


def file_ref(path):
    raw = path.read_bytes()
    return {'path': path.as_posix(), 'bytes': len(raw), 'sha256': digest(raw)}


def lines(text, first, last):
    return textwrap.dedent('\n'.join(text.splitlines()[first - 1:last])) + '\n'


def indent(text, spaces=4):
    return textwrap.indent(text.rstrip() + '\n', ' ' * spaces)


def effect(name, body):
    return name + ' = {\n' + indent(body) + '}\n'


def transition(stage):
    return f'save_scope_value_as = {{ name = lyd_factory_diag_stage value = {stage} }}\ntrigger_event = {NAMESPACE}.{stage}\n'


def heir_log_snapshot(position):
    if position not in ('BEFORE_CREATE', 'AFTER_CREATE', 'AFTER_HOLDER', 'AFTER_RESOLVE'):
        raise ValueError('Unknown heir log position')
    prefix = 'LYD_D2B_HEIR_PROBE_' + position
    return (f'debug_log = "{prefix}_BEGIN"\n'
            'every_in_list = {\n'
            '    variable = lyd_i3b_political_titles\n'
            f'    debug_log = "{prefix}_TITLE"\n'
            '    debug_log_scopes = yes\n'
            '    every_title_heir = {\n'
            f'        debug_log = "{prefix}_HEIR"\n'
            '        debug_log_scopes = yes\n'
            '    }\n'
            '}\n'
            f'debug_log = "{prefix}_END"\n')


def generate(factory, commit, product_name, control='full', *,
             heir_log_probe=False, stop_after_holder=False):
    if control not in ('full', 'transaction-only'):
        raise ValueError('Unknown diagnostic control')
    if type(heir_log_probe) is not bool or type(stop_after_holder) is not bool:
        raise ValueError('Diagnostic flags must be explicit booleans')
    if heir_log_probe and control != 'full':
        raise ValueError('Heir log probe requires the full holder transaction')
    if stop_after_holder and not heir_log_probe:
        raise ValueError('Stop-after-holder requires the heir log probe')
    preamble = lines(commit, 18, 29)
    initial_guard = lines(commit, 12, 16)
    factory_guard = lines(factory, 7, 14)
    capture = lines(factory, 16, 22)
    finish = lines(commit, 31, 66)
    early_failure = lines(factory, 56, 56)
    failure_log = 'debug_log = "LYD_C3_HEAD_FACTORY_REJECTED"\n'
    # The existing reject path continues original postconditions; no false stage.
    opening = 'if = {\n' + indent('limit = {\n' + indent(initial_guard) + '}\n')
    opening += indent(preamble)
    opening += indent('if = {\n' + indent('limit = {\n' + indent(factory_guard) + '}\n' + capture + transition(1)) + '}\n')
    opening += indent('else = {\n' + indent(failure_log + finish + 'lyd_i3b_show_result_effect = yes\n') + '}\n')
    opening += '}\n'
    text = '# DEVELOPMENT ONLY overlay. Generated by build_diagnostic_overlay.py; production is untouched.\n'
    if heir_log_probe:
        text = '# GENERATED FILE: development diagnostic overlay; build_factory_diagnostic.py. Production is untouched.\n'
    text += lines(commit, 3, 9) + '\n'
    text += effect('lyd_i3b_commit_effect', opening) + '\n'
    text += lines(commit, 70, 78) + '\n'
    chunks = {
        20: lines(factory, 23, 23) + lines(factory, 25, 32),
        2: lines(factory, 24, 24) + lines(factory, 33, 36),
        3: lines(factory, 37, 37),
        4: lines(factory, 38, 50),
        5: lines(factory, 51, 51),
        6: lines(factory, 52, 54) + finish,
    }
    if control == 'transaction-only':
        # Match the R34 control's title configuration, then resolve an empty
        # transaction. The saved marker proves execution reached past resolve.
        chunks[20], count = re.subn(r'^\s*set_always_follows_primary_heir = yes\n', '', chunks[20], flags=re.M)
        if count != 1:
            raise ValueError('Expected one primary-heir property')
        chunks[2], count = re.subn(
            r'^scope:new_title = \{\n\s*change_title_holder = \{ holder = root change = scope:lyd_c3_head_change \}\n\}\n',
            '', chunks[2], flags=re.M)
        if count != 1:
            raise ValueError('Expected one atomic holder change')
        chunks[2] += f'set_variable = {{ name = {TRANSACTION_MARKER} value = 1 }}\n'
    if heir_log_probe:
        create = lines(factory, 24, 24)
        holder = lines(factory, 33, 35)
        resolve = lines(factory, 36, 36)
        if create + holder + resolve != chunks[2]:
            raise ValueError('Original atomic holder transaction changed')
        chunks[2] = (heir_log_snapshot('BEFORE_CREATE') + create
                     + heir_log_snapshot('AFTER_CREATE') + holder
                     + heir_log_snapshot('AFTER_HOLDER') + resolve
                     + heir_log_snapshot('AFTER_RESOLVE'))
    for stage, chunk in chunks.items():
        text += effect(f'lyd_factory_diag_d{stage}_effect', chunk + transition(stage)) + '\n'
    trigger = '''# DEVELOPMENT ONLY: continuation identity, not a new mandate.
lyd_factory_diag_continue_trigger = {
    lyd_i3b_cancel_context_trigger = yes
    has_variable = lyd_c3_head_creation_authorized
    exists = scope:lyd_c3_factory_faith
    faith = scope:lyd_c3_factory_faith
    faith = var:lyd_i3b_faith
    rite = var:lyd_i3b_main
    exists = scope:lyd_factory_diag_stage
    scope:lyd_factory_diag_stage = $STAGE$
}
lyd_factory_diag_title_trigger = {
    exists = scope:new_title
    scope:new_title = {
        holder = root
        var:lyd_c2_owned_head_title = 1
        var:lyd_c2_owner_faith = scope:lyd_c3_factory_faith
    }
}
lyd_factory_diag_unheld_title_trigger = {
    exists = scope:new_title
    scope:new_title = {
        NOT = { exists = holder }
        var:lyd_c2_owned_head_title = 1
        var:lyd_c2_owner_faith = scope:lyd_c3_factory_faith
    }
}
lyd_factory_diag_result_trigger = {
    lyd_i3b_result_actor_trigger = yes
    exists = scope:lyd_i3b_actor
    this = scope:lyd_i3b_actor
    var:lyd_i3b_result_serial = scope:lyd_i3b_event_serial
    var:lyd_i3b_result_nonce = scope:lyd_i3b_event_nonce
    exists = scope:lyd_factory_diag_stage
    scope:lyd_factory_diag_stage = 6
}
'''
    events = '# DEVELOPMENT ONLY: no immediate mutators, no timed continuation.\nnamespace = ' + NAMESPACE + '\n\n'
    for stage in STAGE_ORDER:
        if stage == 6:
            guard = 'lyd_factory_diag_result_trigger = yes\n'
            operation = 'lyd_i3b_show_result_effect = yes\n'
        else:
            guard = f'lyd_factory_diag_continue_trigger = {{ STAGE = {stage} }}\n'
            if stage == 1:
                # Reuse the actual original factory limit before title creation.
                guard += factory_guard
            elif stage == 20 or (control == 'transaction-only' and stage == 2):
                guard += 'lyd_factory_diag_unheld_title_trigger = yes\n'
            else:
                guard += 'lyd_factory_diag_title_trigger = yes\n'
            if stage in (3, 4, 5):
                guard += 'faith.religious_head_title = scope:new_title\n'
            next_stage = 20 if stage == 1 else (2 if stage == 20 else stage + 1)
            operation = f'lyd_factory_diag_d{next_stage}_effect = yes\n'
        terminal = (control == 'transaction-only' or stop_after_holder) and stage == 2
        if control == 'transaction-only' and stage == 2:
            guard += f'var:{TRANSACTION_MARKER} = 1\n'
        events += f'{NAMESPACE}.{stage} = {{\n'
        events += '    type = character_event\n    theme = faith\n'
        events += f'    title = lyd_factory_diag_d{stage}_title\n    desc = lyd_factory_diag_d{stage}_desc\n'
        events += '    trigger = {\n' + indent(guard, 8) + '    }\n'
        option_name = 'lyd_factory_diag_stop' if stop_after_holder and stage == 2 else 'lyd_factory_diag_next'
        events += f'    option = {{\n        name = {option_name}\n'
        events += '        trigger = {\n' + indent(guard, 12) + '        }\n'
        if not terminal:
            events += '        hidden_effect = {\n            if = {\n                limit = {\n' + indent(guard, 20) + '                }\n'
            events += indent(operation, 16) + '            }\n        }\n'
        events += '    }\n}\n\n'
    descriptor = f'version="0.0.1"\nname={json.dumps(NAME)}\nsupported_version="1.20.*"\ndependencies={{ {json.dumps(product_name, ensure_ascii=False)} }}\n'
    cn = ['D1：doctrine 与合法授权后', 'D2a：create / owner / 四属性后；未开 transaction', 'D2b：holder / resolve 后', 'D3：SetHoF 后', 'D4：原条件 cleanup 后', 'D5：COA / Title95 后', 'D6：原 postconditions 与 close 后']
    en = ['D1: doctrine and lawful authorization', 'D2a: create / owner / properties; no open transaction', 'D2b: holder / resolve', 'D3: SetHoF', 'D4: original conditional cleanup', 'D5: COA / Title95', 'D6: original postconditions and close']
    if control == 'transaction-only':
        cn[1] = 'D2a：create / owner / 三属性后；未开 transaction'
        en[1] = 'D2a: create / owner / three properties; no open transaction'
        cn[2] = 'D2b：空事务已完成；头衔仍未授封（终点）'
        en[2] = 'D2b: empty transaction completed; title unheld (terminal)'
    locales = {}
    for language, titles in (('english', en), ('simp_chinese', cn)):
        rows = [f'l_{language}:']
        for number, title in zip(STAGE_ORDER, titles):
            rows.append(f' lyd_factory_diag_d{number}_title:0 "{title}"')
            desc = 'DEVELOPMENT DIAGNOSTIC ONLY. Observe cache and save before advancing; this does not prove political protection.' if language == 'english' else '仅开发诊断。推进前读取缓存并保存；本页不证明政治保护通过。'
            rows.append(f' lyd_factory_diag_d{number}_desc:0 "{desc}"')
        caption = 'Advance one diagnostic boundary' if language == 'english' else '仅推进下一个诊断边界'
        rows.append(f' lyd_factory_diag_next:0 "{caption}"')
        if stop_after_holder:
            stop_caption = ('Stop here: save the D2b diagnostic, then quit' if language == 'english'
                            else '到此停止：保存 D2b 诊断，然后退出')
            rows.append(f' lyd_factory_diag_stop:0 "{stop_caption}"')
        locales[f'localization/{language}/lyd_factory_operation_diagnostic_l_{language}.yml'] = '\n'.join(rows) + '\n'
    return {
        'descriptor.mod': descriptor,
        'common/scripted_effects/lyd_i3b_commit_effects.txt': text,
        'common/scripted_triggers/lyd_factory_operation_diagnostic.txt': trigger,
        'events/lyd_factory_operation_diagnostic.txt': events,
        **locales,
    }


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--source-root', required=True)
    parser.add_argument('--source-head', required=True)
    parser.add_argument('--export-report', required=True)
    parser.add_argument('--export-report-sha256', required=True)
    parser.add_argument('--output', required=True)
    parser.add_argument('--control', choices=('full', 'transaction-only'), default='full')
    parser.add_argument('--heir-log-probe', action='store_true',
                        help='Log stock title-heir scopes at four points inside the atomic D2b transaction; no ID/order qualification.')
    parser.add_argument('--stop-after-holder', action='store_true',
                        help='With --heir-log-probe, make D2b a read-only terminal event; no D3 continuation.')
    args = parser.parse_args()
    source = Path(args.source_root).resolve()
    output = Path(args.output).resolve()
    report_path = Path(args.export_report).resolve()
    report_raw = report_path.read_bytes()
    if digest(report_raw) != args.export_report_sha256:
        raise ValueError('Actual export REPORT SHA mismatch')
    report = json.loads(report_raw)
    if re.fullmatch('[0-9a-f]{40}', args.source_head) is None:
        raise ValueError('Require explicit actual full source HEAD')
    if report['source']['head'] != args.source_head or Path(report['source_root']).resolve() != source:
        raise ValueError('Actual export HEAD/root binding mismatch')
    if output.exists():
        raise FileExistsError(output)
    mod = source / 'mod_li_yu_dao'
    input_refs = []
    texts = {}
    for relative, expected in PINS.items():
        path = mod / relative
        raw = path.read_bytes()
        if digest(raw) != expected:
            raise ValueError(f'Production preimage changed: {relative}')
        input_refs.append(file_ref(path))
        texts[relative] = raw.decode('utf-8-sig')
    factory = texts['common/scripted_effects/lyd_c3_head_factory.txt']
    commit = texts['common/scripted_effects/lyd_i3b_commit_effects.txt']
    descriptor = (mod / 'descriptor.mod').read_text(encoding='utf-8-sig')
    product_name = re.search(r'^name="([^"]+)"', descriptor, re.M).group(1)
    files = generate(factory, commit, product_name, args.control,
                     heir_log_probe=args.heir_log_probe, stop_after_holder=args.stop_after_holder)
    output.mkdir(parents=True)
    rows = []
    for relative, text in files.items():
        path = output / relative
        path.parent.mkdir(parents=True, exist_ok=True)
        encoding = 'utf-8-sig' if path.suffix in ('.txt', '.yml', '.mod') else 'utf-8'
        with path.open('x', encoding=encoding, newline='\n') as stream:
            stream.write(text)
        rows.append({'relative_path': relative, **file_ref(path)})
    patch = ''.join(difflib.unified_diff(commit.splitlines(keepends=True), files['common/scripted_effects/lyd_i3b_commit_effects.txt'].splitlines(keepends=True), fromfile='production/common/scripted_effects/lyd_i3b_commit_effects.txt', tofile='diagnostic/common/scripted_effects/lyd_i3b_commit_effects.txt'))
    patch_path = output.parent / (output.name + '.commit-override.patch')
    with patch_path.open('x', encoding='utf-8', newline='\n') as stream:
        stream.write(patch)
    receipt = {
        'schema': 'lyd.factory-operation-diagnostic-overlay.v1',
        'status': 'FILE_ONLY_CANDIDATE_NOT_REGISTERED_OR_LAUNCHED',
        'actual_source_head': args.source_head,
        'actual_export_report': file_ref(report_path),
        'original_production_source_inputs': input_refs,
        'mod_name': NAME,
        'load_after_product_name': product_name,
        'files': rows,
        'production71_modified': False,
        'main_writes': 0,
        'runtime_acceptance': None,
        'diagnostic_business_credit': None,
        'whole_mod': 'NOT_GREEN',
        'patch': file_ref(patch_path),
        'stage_keys': [f'{NAMESPACE}.{stage}' for stage in STAGE_ORDER],
        'stage_labels': {'1': 'D1', '20': 'D2a', '2': 'D2b', '3': 'D3', '4': 'D4', '5': 'D5', '6': 'D6'},
        'D2a_unheld_title_cross_event_and_SAVE_acceptance': None,
        'control': args.control,
        'D2b_transaction': ('create/resolve empty transaction; persistent completion marker after resolve; read-only terminal event'
                            if args.control == 'transaction-only' else 'create/change-holder/resolve atomic; no yield before resolve'),
        'terminal_stage': 2 if args.control == 'transaction-only' or args.stop_after_holder else 6,
        'persistent_completion_marker': TRANSACTION_MARKER if args.control == 'transaction-only' else None,
        'stage_scope': 'lyd_factory_diag_stage',
        'D6': 'Original bookkeeping/postconditions/close completed; only after observing D6 does its option call the original show_result_effect.',
    }
    if args.heir_log_probe:
        receipt['heir_log_probe'] = {
            'positions': ['BEFORE_CREATE', 'AFTER_CREATE', 'AFTER_HOLDER', 'AFTER_RESOLVE'],
            'create_means_transaction_container': True,
            'scope_full_ID_format_qualified': False,
            'iterator_order_qualified': False,
            'getter_may_trigger_lazy_recalculation': True,
            'direct_actor_cache_intermediate_observation': False,
        }
        receipt['stop_after_holder'] = args.stop_after_holder
        if args.stop_after_holder:
            receipt['D2b_transaction'] = 'create/change-holder/resolve atomic; terminal read-only option; no D3 continuation'
    manifest_path = output.parent / (output.name + '.MANIFEST.json')
    with manifest_path.open('x', encoding='utf-8', newline='\n') as stream:
        json.dump(receipt, stream, ensure_ascii=False, indent=2)
        stream.write('\n')
    print(json.dumps({'manifest': file_ref(manifest_path), 'file_count': len(rows), 'runtime_acceptance': None}, ensure_ascii=True))


if __name__ == '__main__':
    main()
