// Included inside xar::game after army_daily_assault_roster_admission_v1.inc.hpp.
struct ArmyPreDatePendingPhysicalRecordV1 {
  std::string status = "unavailable";
  bool ready = false;
  std::string unavailable_reason = "not_demanded";
  std::int32_t native_index = 0;
  std::int64_t physical_slot_i64 = 0;
  std::optional<std::uint8_t> control_raw_u8;
  std::optional<std::uint32_t> stored_hash_raw_u32, key_raw_full_id_u32;
  std::optional<std::int32_t> vector_capacity_raw_i32;
  std::optional<std::string> vector_allocator_identity;
  std::optional<bool> vector_allocator_matches_expected;
  ArmyDailyAssaultRawReferencesV1 references{};
  friend bool operator==(const ArmyPreDatePendingPhysicalRecordV1 &, const ArmyPreDatePendingPhysicalRecordV1 &) = default;
};
struct ArmyPreDatePendingTableFrameV1 {
  std::string status = "unavailable";
  bool ready = false;
  std::string unavailable_reason = "not_demanded";
  std::int32_t schema_version = 1;
  std::optional<std::string> entries_identity;
  std::optional<bool> entries_present, data_is_native_empty_buffer;
  std::optional<std::int32_t> map_count_raw_i32, mask_raw_i32;
  std::optional<std::uint8_t> tail_raw_u8;
  std::optional<std::uint32_t> threshold_bits_u32;
  std::optional<std::int64_t> physical_control_extent_last_slot_i64;
  bool physical_controls_complete = false;
  bool rehash_prefix_complete = false;
  std::int32_t rehash_nonzero_records_observed_i32 = 0;
  std::vector<ArmyPreDatePendingPhysicalRecordV1> records;
  friend bool operator==(const ArmyPreDatePendingTableFrameV1 &, const ArmyPreDatePendingTableFrameV1 &) = default;
};
struct ArmyPreDatePendingArRgV1 {
  std::string status = "unavailable";
  bool ready = false;
  std::string unavailable_reason = "not_demanded";
  std::int32_t native_index = 0;
  std::optional<std::uint32_t> raw_full_id_u32;
  ArmyDailyAssaultOperandResolutionV1 arrg_resolution{};
  std::optional<std::int32_t> current_38_raw_i32;
  std::optional<std::uint32_t> contract_id_144_raw_u32;
  ArmyDailyAssaultOperandResolutionV1 contract_resolution{};
  std::optional<std::uint8_t> contract_flag_b9_raw_u8;
  std::optional<std::int32_t> state_14c_raw_i32;
  std::optional<std::string> original_data_identity;
  std::optional<bool> original_data_present;
  std::optional<std::uint32_t> first_persistent_id_raw_u32;
  ArmyDailyAssaultOperandResolutionV1 persistent_resolution{};
  std::optional<std::uint32_t> persistent_war_id_13c_raw_u32;
  ArmyDailyAssaultOperandResolutionV1 war_resolution{};
  std::optional<std::uint32_t> war_magic_0c_raw_u32;
  std::optional<bool> append_to_pending;
  std::optional<std::uint32_t> append_full_id_u32;
  friend bool operator==(const ArmyPreDatePendingArRgV1 &, const ArmyPreDatePendingArRgV1 &) = default;
};
struct ArmyPreDatePendingSetupV1 {
  std::string status = "unavailable";
  bool ready = false;
  std::string unavailable_reason = "not_demanded";
  std::optional<std::string> entries_identity;
  std::optional<bool> entries_present;
  std::optional<std::int32_t> mask_raw_i32;
  std::optional<std::uint32_t> target_army_full_id_u32, hash_raw_u32;
  std::optional<std::int64_t> home_slot_i64, terminal_physical_slot_i64;
  std::vector<ArmyDailyAssaultPendingProbeV1> probes;
  std::optional<bool> existing_key;
  ArmyDailyAssaultRawReferencesV1 existing_references{};
  std::optional<std::int32_t> map_count_raw_i32;
  std::optional<std::uint8_t> insertion_tail_raw_u8;
  std::optional<std::uint32_t> insertion_threshold_bits_u32;
  friend bool operator==(const ArmyPreDatePendingSetupV1 &, const ArmyPreDatePendingSetupV1 &) = default;
};
struct ArmyPreDatePendingOccurrenceV1 {
  std::string status = "unavailable";
  bool ready = false;
  std::string unavailable_reason = "not_demanded";
  std::int32_t native_index = 0;
  std::optional<std::uint32_t> raw_full_id_u32;
  ArmyDailyAssaultOperandResolutionV1 original_army_resolution{};
  std::optional<std::uint32_t> combat_id_128_raw_u32;
  ArmyDailyAssaultOperandResolutionV1 combat_resolution{};
  std::optional<std::uint32_t> combat_magic_0c_raw_u32;
  std::optional<std::int32_t> army_counter_5c_raw_i32;
  std::optional<bool> pending_mutator_selected;
  ArmyPreDatePendingSetupV1 pending_setup{};
  ArmyDailyAssaultRawReferencesV1 original_arrg_references{};
  std::vector<ArmyPreDatePendingArRgV1> arrg_occurrences;
  friend bool operator==(const ArmyPreDatePendingOccurrenceV1 &, const ArmyPreDatePendingOccurrenceV1 &) = default;
};
struct ArmyCurrentPreDatePendingUpdateInputsV1 {
  std::string status = "unavailable";
  bool ready = false;
  std::string unavailable_reason = "not_demanded";
  std::int32_t schema_version = 1;
  std::string source = "native_current_pre_date_pending_update_inputs";
  std::string stage = "observed_current_pre_date_pending_update_inputs";
  std::optional<bool> manager_loaded;
  std::optional<std::string> manager_identity;
  ArmyDailyAssaultRawReferencesV1 original_roster{}, removal_queue{};
  std::vector<ArmyPreDatePendingOccurrenceV1> occurrences;
  bool raw_roster_references_ready = false;
  bool source_operands_ready = false;
  bool actual_pre_date_callback_ready = false;
  bool actual_tomorrow_roster_ready = false;
  bool full_daily_assault_ready = false;
  bool full_monthly_ready = false;
  std::optional<ArmyPreDatePendingTableFrameV1> pending_table_frame_v1;
  friend bool operator==(const ArmyCurrentPreDatePendingUpdateInputsV1 &, const ArmyCurrentPreDatePendingUpdateInputsV1 &) = default;
};
