// Included inside xar::game. All references retain native occurrence order.
struct ArmyDailyAssaultOperandResolutionV1 {
  std::string status = "unavailable";
  bool ready = false;
  std::string unavailable_reason = "not_demanded";
  std::optional<std::uint32_t> requested_full_id_u32;
  std::optional<bool> registry_loaded;
  std::optional<std::uint32_t> registry_capacity_u32, registry_index_u32;
  std::optional<std::string> indexed_identity;
  std::optional<std::uint32_t> indexed_full_id_u32;
  std::optional<std::string> selection;
  std::optional<bool> used_fallback;
  std::optional<std::string> object_identity;
  std::optional<std::uint32_t> selected_full_id_u32;
  bool selected_object_ready = false;
  std::optional<bool> selected_full_id_read_ready;
  friend bool operator==(const ArmyDailyAssaultOperandResolutionV1 &, const ArmyDailyAssaultOperandResolutionV1 &) = default;
};
struct ArmyDailyAssaultRawReferenceOccurrenceV1 {
  std::string status = "unavailable";
  bool ready = false;
  std::string unavailable_reason = "not_demanded";
  std::int32_t native_index = 0;
  std::optional<std::uint32_t> raw_full_id_u32;
  friend bool operator==(const ArmyDailyAssaultRawReferenceOccurrenceV1 &, const ArmyDailyAssaultRawReferenceOccurrenceV1 &) = default;
};
struct ArmyDailyAssaultRawReferencesV1 {
  std::string status = "unavailable";
  bool ready = false;
  std::string unavailable_reason = "not_demanded";
  bool references_ready = false;
  std::optional<std::int32_t> count_raw_i32;
  std::optional<std::string> data_identity;
  std::optional<bool> data_present;
  std::vector<ArmyDailyAssaultRawReferenceOccurrenceV1> occurrences;
  std::int32_t observed_occurrence_count = 0;
  friend bool operator==(const ArmyDailyAssaultRawReferencesV1 &, const ArmyDailyAssaultRawReferencesV1 &) = default;
};
struct ArmyDailyAssaultRelationProbeV1 {
  std::int32_t native_index = 0;
  std::string kind;
  std::int64_t slot_index_i64 = 0;
  std::optional<std::uint32_t> key_character_id_raw_u32;
  friend bool operator==(const ArmyDailyAssaultRelationProbeV1 &, const ArmyDailyAssaultRelationProbeV1 &) = default;
};
struct ArmyDailyAssaultRelationLookupV1 {
  std::string status = "unavailable";
  bool ready = false;
  std::string unavailable_reason = "not_demanded";
  std::optional<std::string> component_identity;
  std::optional<bool> component_present;
  std::optional<std::string> table_data_identity;
  std::optional<bool> table_data_present;
  std::optional<std::int32_t> table_count_raw_i32;
  std::optional<std::uint32_t> target_character_full_id_raw_u32;
  std::vector<ArmyDailyAssaultRelationProbeV1> probes;
  std::optional<std::int64_t> candidate_slot_index_i64;
  std::optional<std::string> selection;
  std::optional<std::string> default_relationship_identity;
  std::optional<bool> default_relationship_present;
  std::optional<std::string> selected_relationship_identity;
  std::optional<bool> selected_relationship_present;
  std::optional<std::uint32_t> selected_relationship_war_id_raw_u32;
  friend bool operator==(const ArmyDailyAssaultRelationLookupV1 &, const ArmyDailyAssaultRelationLookupV1 &) = default;
};
struct ArmyDailyAssaultAdmissionGateV1 {
  std::string status = "unavailable";
  bool ready = false;
  std::string unavailable_reason = "not_demanded";
  std::optional<bool> verdict;
  std::optional<std::uint32_t> original_army_unit_id_raw_u32;
  ArmyDailyAssaultOperandResolutionV1 original_unit_resolution{};
  std::optional<std::uint32_t> original_unit_kind_raw_u32;
  std::optional<std::string> original_unit_province_identity;
  std::optional<bool> original_unit_province_present;
  std::optional<std::uint32_t> original_province_identity_raw_u32;
  std::optional<std::string> selected_province_comparison_identity;
  std::optional<std::uint32_t> selected_province_comparison_identity_raw_u32;
  std::optional<std::int32_t> original_unit_counter_170_raw_i32;
  std::optional<std::uint32_t> associated_army_id_raw_u32;
  ArmyDailyAssaultOperandResolutionV1 associated_army_resolution{};
  std::optional<std::uint32_t> province_siege_id_raw_u32;
  std::optional<std::int32_t> province_counter_850_raw_i32;
  std::optional<std::uint8_t> associated_army_flag_1d4_raw_u8, associated_army_flag_1ec_raw_u8;
  std::optional<std::uint32_t> associated_army_unit_id_raw_u32;
  ArmyDailyAssaultOperandResolutionV1 associated_unit_resolution{};
  std::optional<std::uint32_t> associated_unit_character_id_raw_u32;
  ArmyDailyAssaultOperandResolutionV1 associated_character_resolution{};
  std::optional<std::uint32_t> province_character_id_73c_raw_u32;
  std::optional<std::string> native_2c099f0_character_identity;
  std::optional<std::string> native_2c099f0_province_identity;
  std::optional<bool> native_2c099f0_third_argument_is_null;
  bool native_2c099f0_returned = false;
  std::optional<std::int32_t> native_2c099f0_classification_raw_i32;
  ArmyDailyAssaultOperandResolutionV1 province_character_resolution{};
  std::optional<std::uint32_t> associated_character_full_id_raw_u32, province_character_full_id_raw_u32;
  ArmyDailyAssaultRelationLookupV1 relation_lookup{};
  ArmyDailyAssaultOperandResolutionV1 selected_war_resolution{};
  std::optional<std::uint8_t> selected_war_ended_358_raw_u8;
  friend bool operator==(const ArmyDailyAssaultAdmissionGateV1 &, const ArmyDailyAssaultAdmissionGateV1 &) = default;
};
struct ArmyDailyAssaultPendingProbeV1 {
  std::int32_t native_index = 0;
  std::int64_t physical_slot_i64 = 0;
  std::uint8_t distance_raw_u8 = 0;
  std::optional<std::uint8_t> control_raw_u8;
  std::optional<std::uint32_t> key_raw_full_id_u32;
  friend bool operator==(const ArmyDailyAssaultPendingProbeV1 &, const ArmyDailyAssaultPendingProbeV1 &) = default;
};
struct ArmyDailyAssaultPendingSelectionV1 {
  std::string status = "unavailable";
  bool ready = false;
  std::string unavailable_reason = "not_demanded";
  std::optional<std::string> entries_identity;
  std::optional<bool> entries_present;
  std::optional<std::int32_t> mask_raw_i32;
  std::optional<std::uint8_t> tail_distance_raw_u8;
  std::optional<std::int32_t> end_slot_raw_i32;
  std::optional<std::uint32_t> target_army_full_id_u32, hash_raw_u32;
  std::optional<std::int64_t> home_slot_i64;
  std::vector<ArmyDailyAssaultPendingProbeV1> probes;
  std::optional<std::int64_t> selected_physical_slot_i64;
  std::optional<bool> selected_is_end_marker;
  std::optional<std::uint8_t> selected_control_raw_u8;
  ArmyDailyAssaultRawReferencesV1 suppression_references{};
  friend bool operator==(const ArmyDailyAssaultPendingSelectionV1 &, const ArmyDailyAssaultPendingSelectionV1 &) = default;
};
struct ArmyDailyAssaultArRgAdmissionOccurrenceV1 {
  std::string status = "unavailable";
  bool ready = false;
  std::string unavailable_reason = "not_demanded";
  std::int32_t native_index = 0;
  std::optional<std::uint32_t> raw_full_id_u32;
  std::optional<bool> pending_contains, append;
  friend bool operator==(const ArmyDailyAssaultArRgAdmissionOccurrenceV1 &, const ArmyDailyAssaultArRgAdmissionOccurrenceV1 &) = default;
};
struct ArmyDailyAssaultRosterAdmissionOccurrenceV1 {
  std::string status = "unavailable";
  bool ready = false;
  std::string unavailable_reason = "not_demanded";
  std::int32_t native_index = 0;
  std::optional<std::uint32_t> raw_full_id_u32;
  ArmyDailyAssaultOperandResolutionV1 original_army_resolution{};
  ArmyDailyAssaultAdmissionGateV1 gate{};
  std::optional<std::uint32_t> caller_army_unit_id_raw_u32;
  ArmyDailyAssaultOperandResolutionV1 caller_unit_resolution{};
  std::optional<std::string> caller_province_identity;
  std::optional<bool> caller_province_present, caller_used_province_fallback;
  std::optional<std::uint32_t> caller_province_siege_id_raw_u32;
  ArmyDailyAssaultOperandResolutionV1 siege_resolution{};
  std::optional<std::uint8_t> siege_flag_44c_raw_u8;
  std::optional<std::uint32_t> selected_army_full_id_raw_u32;
  std::optional<bool> removal_contains_selected_army;
  bool army_append_ready = false;
  std::optional<bool> army_append;
  std::optional<std::uint32_t> army_append_siege_full_id_u32, army_append_full_id_u32;
  ArmyDailyAssaultPendingSelectionV1 pending_selection{};
  ArmyDailyAssaultRawReferencesV1 original_arrg_references{};
  std::vector<ArmyDailyAssaultArRgAdmissionOccurrenceV1> arrg_occurrences;
  bool arrg_append_ready = false;
  std::optional<std::vector<std::uint32_t>> arrg_append_full_ids_u32;
  friend bool operator==(const ArmyDailyAssaultRosterAdmissionOccurrenceV1 &, const ArmyDailyAssaultRosterAdmissionOccurrenceV1 &) = default;
};
struct ArmyCurrentDailyAssaultRosterAdmissionV1 {
  std::string status = "unavailable";
  bool ready = false;
  std::string unavailable_reason = "not_demanded";
  std::int32_t schema_version = 1;
  std::string source = "native_current_daily_assault_roster_admission";
  std::string stage = "observed_current_standalone_2a99b40_admission";
  std::optional<bool> manager_loaded;
  std::optional<std::string> manager_identity;
  ArmyDailyAssaultRawReferencesV1 original_roster{}, removal_queue{};
  std::vector<ArmyDailyAssaultRosterAdmissionOccurrenceV1> occurrences;
  bool raw_roster_references_ready = false;
  bool original_army_selections_ready = false;
  bool army_appends_ready = false;
  bool arrg_appends_ready = false;
  bool conditional_admission_ready = false;
  bool actual_next_callback_ready = false;
  bool actual_tomorrow_roster_ready = false;
  bool full_future_table_placement_ready = false;
  bool full_daily_assault_ready = false;
  friend bool operator==(const ArmyCurrentDailyAssaultRosterAdmissionV1 &, const ArmyCurrentDailyAssaultRosterAdmissionV1 &) = default;
};
