// Included inside xar::game, after ContextSourcePropertiesV1.
struct ContextSourceMiddleKeyProbeV1 {
  std::int32_t native_index = 0;
  std::uint16_t key_u16 = 0;
  friend bool operator==(const ContextSourceMiddleKeyProbeV1 &, const ContextSourceMiddleKeyProbeV1 &) = default;
};
struct ContextSourceMiddleRankFamilyV1 {
  std::string status = "unavailable";
  bool ready = false;
  std::int32_t native_index = 0;
  std::optional<std::int64_t> score_q64;
  std::optional<std::int32_t> override_raw;
  std::optional<std::int32_t> threshold_count;
  std::optional<bool> threshold_array_present;
  std::optional<std::vector<std::int64_t>> thresholds_consumed_q64;
  std::optional<std::int32_t> rank_raw;
  std::optional<std::int32_t> manager_count_raw;
  std::optional<std::string> definition_selection;
  std::optional<std::string> definition_identity;
  std::optional<std::int32_t> definition_gate_raw;
  std::optional<bool> admitted;
  std::uint16_t weight_key_u16 = 0;
  std::optional<bool> weight_carrier_present;
  std::optional<bool> weight_owner_matches;
  std::optional<std::string> weight_source_selection;
  std::optional<std::string> weight_source_identity;
  std::optional<std::int32_t> weight_default_guard_raw;
  std::optional<std::int32_t> weight_keys_count_raw;
  std::optional<std::vector<ContextSourceMiddleKeyProbeV1>> weight_key_probes;
  std::optional<bool> weight_found;
  std::optional<std::int32_t> weight_native_index;
  std::optional<std::int64_t> weight_value_q64;
  std::optional<std::int64_t> weight_q64;
  std::optional<std::string> property_identity;
  std::optional<ContextSourcePropertiesV1> property_block;
  std::string reason;
  friend bool operator==(const ContextSourceMiddleRankFamilyV1 &, const ContextSourceMiddleRankFamilyV1 &) = default;
};
struct ContextSourceMiddle260V1 {
  std::string status = "unavailable";
  bool ready = false;
  std::optional<bool> component_present;
  std::vector<ContextSourceMiddleRankFamilyV1> families;
  std::string reason;
  friend bool operator==(const ContextSourceMiddle260V1 &, const ContextSourceMiddle260V1 &) = default;
};
struct ContextSourceMiddleModifierV1 {
  std::int32_t native_index = 0;
  std::optional<std::string> modifier_identity;
  std::optional<std::uint8_t> token_u8;
  std::optional<std::uint8_t> modifier_count_u8;
  std::optional<std::string> base_selection;
  std::optional<std::string> property_identity;
  std::optional<std::int32_t> gate_raw;
  std::optional<bool> admitted;
  std::optional<ContextSourcePropertiesV1> property_block;
  std::string reason;
  friend bool operator==(const ContextSourceMiddleModifierV1 &, const ContextSourceMiddleModifierV1 &) = default;
};
struct ContextSourceMiddleContextV1 {
  std::string status = "unavailable";
  bool ready = false;
  std::int32_t native_index = 0;
  std::optional<std::int32_t> requested_full_id_raw;
  std::optional<std::string> selection;
  std::optional<std::string> context_identity;
  std::optional<std::uint32_t> magic_raw;
  std::optional<std::int32_t> full_id_raw;
  std::optional<bool> admitted;
  std::optional<std::int32_t> owner_full_id_raw;
  std::optional<std::int32_t> character_full_id_raw;
  std::optional<bool> owner_matches;
  std::optional<std::int32_t> modifier_count;
  std::optional<bool> modifier_array_present;
  std::optional<bool> token_array_present;
  std::optional<std::vector<ContextSourceMiddleModifierV1>> modifier_rows;
  std::optional<std::string> terminal_property_identity;
  std::optional<ContextSourcePropertiesV1> terminal_property_block;
  std::string reason;
  friend bool operator==(const ContextSourceMiddleContextV1 &, const ContextSourceMiddleContextV1 &) = default;
};
struct ContextSourceMiddleContextFamilyV1 {
  std::string status = "unavailable";
  bool ready = false;
  std::optional<std::string> header_selection;
  std::optional<std::int32_t> count;
  std::optional<bool> array_present;
  std::optional<std::vector<ContextSourceMiddleContextV1>> rows;
  std::string reason;
  friend bool operator==(const ContextSourceMiddleContextFamilyV1 &, const ContextSourceMiddleContextFamilyV1 &) = default;
};
struct ContextSourceMiddleFb10V1 {
  std::string status = "unavailable";
  bool ready = false;
  std::optional<bool> land_present;
  ContextSourceMiddleContextFamilyV1 preferred;
  ContextSourceMiddleContextFamilyV1 list_218;
  ContextSourceMiddleContextFamilyV1 list_248;
  std::string reason;
  friend bool operator==(const ContextSourceMiddleFb10V1 &, const ContextSourceMiddleFb10V1 &) = default;
};
struct ContextSourceMiddleHelpersV1 {
  std::string status = "unavailable";
  bool ready = false;
  std::int32_t character_id = -1;
  ContextSourceMiddle260V1 helper_291f260;
  ContextSourceMiddleFb10V1 helper_291fb10;
  std::string reason;
  friend bool operator==(const ContextSourceMiddleHelpersV1 &, const ContextSourceMiddleHelpersV1 &) = default;
};
