# Qualified Lifestyle trigger frontier providers; original stock/formal/transport targets remain.
target_sources(xar_ck3_12002_runtime PRIVATE
  src/lifestyle_trigger_frontier_12004.cpp
  src/trigger_descriptor_validator_372e0ae_12004.cpp
  src/lifestyle_trigger_preferred_kind_12004.cpp
  src/lifestyle_trigger_scope_mask_12004.cpp
  src/lifestyle_trigger_final_c8_source_12004.cpp)

# Actual successor link used ten new linked TUs plus ten qualified production TUs.
# Formal wire and transport were compile-only checks and are excluded from this binary.
if(BUILD_TESTING AND WIN32)
  add_executable(lifestyle_trigger_frontier_12004_new_compound EXCLUDE_FROM_ALL
    src/lifestyle_trigger_frontier_12004.cpp
    src/trigger_descriptor_validator_372e0ae_12004.cpp
    src/lifestyle_trigger_preferred_kind_12004.cpp
    src/lifestyle_trigger_scope_mask_12004.cpp
    src/lifestyle_trigger_final_c8_source_12004.cpp
    src/ck3_12004_stock_perk_legality.cpp
    tests/lifestyle_trigger_frontier_12004_new_compound.cpp
    tests/trigger_descriptor_validator_372e0ae_12004_fresh_cases.cpp
    tests/lifestyle_trigger_preferred_kind_12004_new_cases.cpp
    tests/stock_perk_trigger_frontier_12004_new_focus.cpp
    src/lifestyle_perk_predicate_inputs_12004.cpp
    src/lifestyle_perk_predicate_288b1b0_12004.cpp
    src/lifestyle_owned_perk_collection_2919340_12004.cpp
    src/construction_collection_predicate_a11cc0_12004.cpp
    src/lifestyle_character_scope_12004.cpp
    src/m4_factor_actor_inner_init_12004.cpp
    src/lifestyle_perk_truth_producer_12004.cpp
    src/lifestyle_perk_final_31ebe50_readonly_12004.cpp
    src/source_auto_accept_trigger_condition_12004.cpp
    src/trigger_scope_table_provider_3795a60_12004.cpp)
  target_include_directories(lifestyle_trigger_frontier_12004_new_compound PRIVATE include)
  target_compile_features(lifestyle_trigger_frontier_12004_new_compound PRIVATE cxx_std_20)
  target_link_libraries(lifestyle_trigger_frontier_12004_new_compound PRIVATE kernel32)
  target_compile_definitions(lifestyle_trigger_frontier_12004_new_compound PRIVATE
    NOMINMAX
    UNICODE
    WIN32_LEAN_AND_MEAN
    XAR_CK3_ENABLE_FEUDAL_1066_BOOKMARK_MODEL_PRIVATE_V1=1
    XAR_CK3_ENABLE_FEUDAL_1066_SELECTED_BOOKMARK_START_PRIVATE_V1=1
    XAR_CK3_ENABLE_G2_ACTIVE_SCHEME_PRIVATE_CANDIDATE_V1=1
    XAR_CK3_ENABLE_G2_ACTIVE_SCHEME_SWAY_FORMAL_PRIVATE_ACTION_V1=1
    XAR_CK3_ENABLE_G2_ACTIVE_SCHEME_SWAY_OUTCOME_OPINION_PRIVATE_QUERY_V1=1
    XAR_CK3_ENABLE_G2_ACTIVITY_COST_SLOT12_PASSIVE_PRIVATE_V1=1
    XAR_CK3_ENABLE_G2_ACTIVITY_FEAST_GUEST_CANDIDATE_PRIVATE_V1=1
    XAR_CK3_ENABLE_G2_ACTIVITY_FEAST_GUEST_OPINION_PRIVATE_V1=1
    XAR_CK3_ENABLE_G2_ACTIVITY_FEAST_GUEST_RULE_PROVENANCE_PRIVATE_V1=1
    XAR_CK3_ENABLE_G2_ACTIVITY_FEAST_GUEST_RULE_TOGGLE_PRIVATE_V1=1
    XAR_CK3_ENABLE_G2_ACTIVITY_FEAST_PLANNER_OPEN_PRIVATE_V1=1
    XAR_CK3_ENABLE_G2_ACTIVITY_FEAST_STAGE5_START_PRIVATE_V1=1
    XAR_CK3_ENABLE_G2_ACTIVITY_STAGE1_CONFIRM_PRIVATE_V1=1
    XAR_CK3_ENABLE_G2_ACTIVITY_STAGE1_OPTION_READ_PRIVATE_V1=1
    XAR_CK3_ENABLE_G2_ACTIVITY_STAGE2_DESTINATION_PRIVATE_V1=1
    XAR_CK3_ENABLE_G2_ACTIVITY_STAGE2_GATE_READ_PRIVATE_V1=1
    XAR_CK3_ENABLE_G2_ACTIVITY_STAGE2_LOCATION_READ_PRIVATE_V1=1
    XAR_CK3_ENABLE_G2_ACTIVITY_STAGE2_OPTION_READ_PRIVATE_V1=1
    XAR_CK3_ENABLE_G2_ACTIVITY_STAGE5_CANSTART_PRIVATE_V1=1
    XAR_CK3_ENABLE_G2_ACTIVITY_STAGE5_FEAST_FULL_COST_PRIVATE_V1=1
    XAR_CK3_ENABLE_G2_ACTIVITY_STAGE5_GOLD_COST_PRIVATE_V1=1
    XAR_CK3_ENABLE_G2_COUNCIL_APPLICATION_MAIN_PRIVATE_ROUTE_V1=1
    XAR_CK3_ENABLE_G2_COUNCIL_ASSIGN_PRIVATE_ACTION_GATE_V1=1
    XAR_CK3_ENABLE_G2_COUNCIL_FINAL_GATE_PRIVATE_QUERY_V1=1
    XAR_CK3_ENABLE_G2_FACTION_GIFT_MITIGATION_ASYNC_PRIVATE_GLUE_V1=1
    XAR_CK3_ENABLE_G2_GOVERNMENT_RUNTIME_PRIVATE_QUERY_V1=1
    XAR_CK3_ENABLE_G2_M5_ALLIANCE_PROJECTION_PRIVATE_QUERY_V1=1
    XAR_CK3_ENABLE_G2_M5_CHILD_MATRILINEAL_PRIVATE_ACTION_V1=1
    XAR_CK3_ENABLE_G2_M5_FAMILY_OBLIGATIONS_PRIVATE_QUERY_V1=1
    XAR_CK3_ENABLE_G2_M5_HEIR_MARRIAGE_PRIVATE_ACTION_V1=1
    XAR_CK3_ENABLE_G2_M5_RANKED_MARRIAGE_PRIVATE_QUERY_V1=1
    XAR_CK3_ENABLE_G2_M5_WAR_CASH_PRIVATE_QUERY_V1=1
    XAR_CK3_ENABLE_G2_PLAYER_CLERGY_APPOINTMENT_PRIVATE_QUERY_V1=1
    XAR_CK3_ENABLE_G2_PLAYER_CONSTRUCTION_VIEW_PROBE_PRIVATE_V1=1
    XAR_CK3_ENABLE_G2_PLAYER_EPIDEMIC_RECOVERY_PRIVATE_QUERY_V1=1
    XAR_CK3_ENABLE_G2_PLAYER_EPIDEMIC_TREATMENT_PRIVATE_QUERY_V1=1
    XAR_CK3_ENABLE_G2_PLAYER_FACTION_ALERTS_PRIVATE_QUERY_V1=1
    XAR_CK3_ENABLE_G2_PLAYER_LIFESTYLE_FORMAL_WIRE_PRIVATE_V1=1
    XAR_CK3_ENABLE_G2_PLAYER_RELIGION_AI_REFORM_INPUTS_PRIVATE_QUERY_V1=1
    XAR_CK3_ENABLE_G2_PLAYER_RELIGION_CONTEXT_PRIVATE_QUERY_V1=1
    XAR_CK3_ENABLE_G2_PLAYER_RELIGION_DOCTRINES_PRIVATE_QUERY_V1=1
    XAR_CK3_ENABLE_G2_PLAYER_RELIGION_DOCTRINE_CATALOGUE_PRIVATE_QUERY_V1=1
    XAR_CK3_ENABLE_G2_PLAYER_RELIGION_DOCTRINE_KNOWLEDGE_PRIVATE_QUERY_V1=1
    XAR_CK3_ENABLE_G2_PLAYER_RELIGION_DRAFT_DOCTRINE_CHOICES_PRIVATE_QUERY_V1=1
    XAR_CK3_ENABLE_G2_PLAYER_RELIGION_DRAFT_GROUPS_PRIVATE_QUERY_V1=1
    XAR_CK3_ENABLE_G2_PLAYER_RELIGION_DRAFT_RESOURCE_COSTS_PRIVATE_QUERY_V1=1
    XAR_CK3_ENABLE_G2_PLAYER_RELIGION_DRAFT_TENET_CHOICES_PRIVATE_QUERY_V1=1
    XAR_CK3_ENABLE_G2_PLAYER_RELIGION_HOSTILITY_PRIVATE_QUERY_V1=1
    XAR_CK3_ENABLE_G2_PLAYER_RELIGION_NUMERIC_SPECIAL_PARAMETERS_PRIVATE_QUERY_V1=1
    XAR_CK3_ENABLE_G2_PLAYER_RELIGION_PERSONAL_PARAMETERS_PRIVATE_QUERY_V1=1
    XAR_CK3_ENABLE_G2_PLAYER_RELIGION_REFORM_CONTEXT_PRIVATE_QUERY_V1=1
    XAR_CK3_ENABLE_G2_PLAYER_RELIGION_TENETS_PRIVATE_QUERY_V1=1
    XAR_CK3_ENABLE_G2_PLAYER_RITE_GOVERNANCE_PRIVATE_QUERY_V1=1
    XAR_CK3_ENABLE_G2_PLAYER_RITE_MEMBERS_PRIVATE_QUERY_V1=1
    XAR_CK3_ENABLE_G2_PLAYER_WORLD_BUILDING_ACTION_PRIVATE_V1=1
    XAR_CK3_ENABLE_G2_PRISONER_CHILD_RELATION_PRIVATE_V1=1
    XAR_CK3_ENABLE_G2_PRISONER_COLLECTION_PRIVATE_QUERY_V1=1
    XAR_CK3_ENABLE_G2_PRISONER_RANSOM_ACTION_PRIVATE_V1=1
    XAR_CK3_ENABLE_G2_PRISONER_RANSOM_PREVIEW_PRIVATE_V1=1
    XAR_CK3_ENABLE_G2_PRISONER_RELEASE_PREVIEW_PRIVATE_V1=1
    XAR_CK3_ENABLE_G2_PRISONER_TITLE_TIER_PRIVATE_V1=1
    XAR_CK3_ENABLE_G2_REALM_LAW_ENACT_PRIVATE_V1=1
    XAR_CK3_ENABLE_G2_REALM_LAW_PAUSED_PRIVATE_QUERY_V1=1
    XAR_CK3_ENABLE_G2_RELIGION_CONVERSION_PRIVATE_QUERY_V1=1
    XAR_CK3_ENABLE_ORDINARY_HOLY_WAR_DECLARATION_CONTEXT_PRIVATE_V1=1
    _UNICODE
    WIN32
    _WINDOWS
    XAR_CK3_ENABLE_G2_ARMY_LATE_EVENT_OBSERVER_V1=1
    XAR_CK3_ENABLE_G2_ARMY_COMPILED_EFFECT_OBSERVER_V1=1
    XAR_BRIDGE_ENABLE_12004_PERSON_INSTALLED_TRANSFER_CAPTURE=1
    _ITERATOR_DEBUG_LEVEL=0)
  if(MSVC)
    set_property(TARGET lifestyle_trigger_frontier_12004_new_compound PROPERTY MSVC_RUNTIME_LIBRARY MultiThreadedDLL)
    target_compile_options(lifestyle_trigger_frontier_12004_new_compound PRIVATE
      /O2 /Ob2 /EHsc /W4 /WX /permissive- /utf-8 /UNDEBUG)
  endif()
  # Explicitly selected only; one fresh wire-output-directory argument, no automatic test run.
endif()
