"""28 individually authored cultivation dilemmas, appended to the immutable eight.

Stories are anonymous designed situations. Source keys come from each existing
catalogue route; no story is attributed to an historical person's biography.
Only the existing exact integer player-resource/learning-XP schema is used.
"""


def build_additional_practices(Practice, PracticeOption, rites):
    def o(key, zh, en, tz, te, gold=0, piety=0, prestige=0, stress=0, xp=0):
        return PracticeOption(key, zh, en, tz, te, gold_cost=gold,
                              piety_change=piety, prestige_change=prestige,
                              stress_change=stress, learning_xp=xp)

    def p(code, tz, te, dz, de, choices, bz, be):
        return Practice(code, tz, te, dz, de, choices, bz, be, rites[code].source_keys)

    return (
        p("R04", "灾异之后，谁当省过？", "Who Must Reflect after a Portent?",
          "一场异象引起议论，讲席有人从《春秋》褒贬追问失德，有人急于把它解释成对仇人的天罚。祭前的敬畏若只用来指责别人，还能成为自己的省察吗？",
          "An unusual occurrence prompts debate. Some read moral judgments in the Spring and Autumn Annals; others declare that Heaven has punished their enemies. Can reverence before an offering become self-examination if it is directed only at others?",
          (o("a", "先检我所失，不借灾异推过。", "Examine my own faults before blaming others.",
             "以谴告之说要求自身改过，承担损失颜面与省察的压力。", "Treat the warning as a demand for personal correction, accepting lost standing and the burden of reflection.", 5, 40, -10, 10, 25),
           o("b", "并读经说，保留不同的解释。", "Read the commentaries together and preserve disagreement.",
             "以公羊经义讨论责任，不把争议的征兆当作已证天罚。", "Discuss responsibility through Gongyang interpretation without presenting a disputed sign as proven divine punishment.", 20, 25, 10, 5, 40),
           o("c", "宣称天只责我的对手。", "Declare that Heaven condemns only my opponents.",
             "借天命之名取得声势，却避开自身所当承担的义。", "Gain attention through claims about Heaven while evading one's own moral responsibility.", 10, -30, 25, -5, 0)),
          "董氏相关公羊与灾异解释的匿名情境；不把所有今文经学等同董氏，不生成真实天罚或灾害。",
          "An anonymous dilemma concerning Dong's Gongyang and portent interpretation; it neither equates all New Text learning with Dong nor creates divine punishment or disasters."),
        p("R05", "名物异文与祭器", "Variant Readings and Ritual Vessels",
          "一件旧祭器的名称与传注不同，新抄本又给出另一种读法。礼生盼你立即定说，你却尚未辨明经文、旧注与实物各自能证明什么。",
          "An old ritual vessel bears a name that differs from the commentaries, while a new copy offers another reading. The attendants want an immediate ruling, but the text, glosses and object do not yet establish the same conclusion.",
          (o("a", "辨故训与实物，暂缓定说。", "Compare old glosses and the object before deciding.",
             "把名物考证用于礼义，付出反复查验的工夫。", "Use historical particulars to understand ritual, accepting the effort of repeated examination.", 10, 25, -5, 10, 45),
           o("b", "列明异说，依可据之礼备祭。", "Record the variants and prepare the supported form of the rite.",
             "保留传注的限度，也让祭前准备有可说明的经据。", "Acknowledge the limits of the commentaries while preparing an offering on explainable textual grounds.", 25, 40, 10, 5, 25),
           o("c", "器物贵重，自可证明其正确。", "Its expense must prove that the vessel is correct.",
             "以财力代替经据，外观的声望难以成为明礼之学。", "Expense replaces evidence; impressive appearance cannot establish ritual understanding.", 35, -20, 20, -5, 0)),
          "以汉代经传、故训与名物为素材，不假定古文家构成统一的无神论宗派。",
          "Draws on Han texts, glosses and ritual particulars without presenting Old Text scholars as a uniform atheist denomination."),
        p("R08", "象、言与所指之义", "Images, Words and Their Meaning",
          "讲《易》时，众人争相临摹卦象，却少有人说明它们所指的义。有人还建议祭前增添符饰，声称图样越多便越能掌握天道。",
          "At a discussion of the Changes, everyone copies the images but few explain their meaning. Some propose adding symbolic ornaments before the offering, claiming that more diagrams give greater command of Heaven's workings.",
          (o("a", "循言象求义，再问其根本。", "Seek meaning through words and images, then examine the root.",
             "崇本并非无需读经，须从解释进入所要理解的义。", "Seeking the root does not dispense with reading; interpretation must lead toward understanding.", 10, 25, -5, 10, 45),
           o("b", "减去无谓符饰，使习礼归于本意。", "Remove needless ornaments and attend to the rite's purpose.",
             "不拘装饰而保留合宜仪节，把理解用于亲身习礼。", "Set aside needless display while preserving fitting ritual forms and personal practice.", 15, 40, 5, -5, 25),
           o("c", "凭更多符饰宣称已能操纵天道。", "Claim control of Heaven through more symbolic ornaments.",
             "执图样为实效，背离求义；此宣称不会产生真实法术。", "Treating diagrams as power abandons interpretation; the claim creates no real magic.", 30, -25, 20, -5, 0)),
          "王弼式经典解释的跨儒道设计；不把贵无等同现代无神论，亦不生成占验必中的能力。",
          "A cross-traditional design based on Wang Bi's interpretation; nonbeing is not equated with modern atheism, and no infallible divination is granted."),
        p("R09", "性分与强作", "Capacity and Forced Conformity",
          "习礼中，一位学者要求所有人照同一种姿态、同一种声调完成仪节。新学者愈学愈拘，原有的责任也被搁置。何种自得才与名教相容？",
          "During ritual rehearsal, a scholar demands identical gestures and tones from everyone. New pupils become constrained and neglect their existing responsibilities. What kind of self-realization can remain compatible with moral roles?",
          (o("a", "因各人性分施教，仍使其履行礼责。", "Teach according to capacities while preserving ritual duties.",
             "自得不取消责任，须花工夫辨其所能而使礼有实。", "Self-realization does not erase responsibility; teaching must discern capacities and make ritual effective.", 20, 40, -5, 5, 35),
           o("b", "去强作而安其分，重新习礼。", "Set aside forced imitation and rehearse within fitting roles.",
             "减少勉强模仿的负担，保留各自所当承担的仪节。", "Reduce forced imitation while retaining each person's responsibilities within the rite.", 5, 30, 5, -10, 25),
           o("c", "既言自然，失礼失职也无需问。", "Call everything natural and ignore neglected duties.",
             "把自然当作逃避责任的借口，不能由此证明自得。", "Invoking nature to evade responsibility does not establish self-realization.", 0, -25, 15, -5, 0)),
          "郭象性分、自得与名教自然的匿名工夫题，不把独化解为王弼贵无，不改变人物身份等级。",
          "An anonymous cultivation case concerning Guo Xiang's capacities, self-realization and moral roles; it does not equate self-transformation with Wang Bi's nonbeing or change social ranks."),
        p("R11", "祭圣之日，何谓传道？", "What Does Transmission Mean at an Offering to the Sages?",
          "祭圣之前，讲席论及师道与人伦。有门人提议只须高声排斥佛道，便能证明真传；另一人却问，传道者是否先履行了眼前的仁义。",
          "Before an offering to the sages, the assembly discusses teachers and human obligations. One pupil claims that denouncing Buddhists and Daoists proves true transmission; another asks whether the claimant has practiced humaneness and rightness.",
          (o("a", "据仁义辩原道，也审我之所行。", "Examine the Way through humaneness and my own conduct.",
             "把论辩落在人伦与师道，承受被问难的压力。", "Ground argument in human obligations and teaching, accepting the pressure of criticism.", 10, 30, -10, 10, 45),
           o("b", "奉祀先师，亲自承担授业与照料。", "Honor the teachers and undertake teaching and care.",
             "圣道承传须有躬行，仪节与承担不能只停留于口号。", "Transmission requires conduct; offerings and duties must extend beyond slogans.", 25, 45, 10, 5, 25),
           o("c", "让不相干的佛道人物替我背过。", "Blame unrelated Buddhists and Daoists for my faults.",
             "排斥他人可以招来声势，却不能代替仁义和改过。", "Hostility may attract attention but cannot substitute for moral conduct and correction.", 5, -30, 25, -5, 0)),
          "以韩愈原道、师道的义理为素材；选项不发动迫害、改宗或对所有佛道人物的永久关系惩罚。",
          "Draws on Han Yu's account of the Way and teaching; choices do not trigger persecution, conversion or permanent hostility toward every Buddhist or Daoist."),
        p("R12", "复性与未平之情", "Returning to Nature amid Unsettled Feelings",
          "祭前省察时，你发现愤怒与求名不断搅动心念。有学者劝你澄心，也有人说只要毫无悲喜便已复性。诚如何贯通静养与行事？",
          "Before the offering, anger and the wish for acclaim disturb your reflection. One scholar advises calming the heart; another claims that having no grief or joy would prove restored nature. How can sincerity join stillness and conduct?",
          (o("a", "澄心去妄，辨明纷扰所从来。", "Calm the heart and examine the source of turbulent thoughts.",
             "静养用于去妄，暂离求名以减轻心念纷扰。", "Use stillness to examine turbulent thoughts and step away from the pursuit of acclaim.", 5, 35, -5, -10, 25),
           o("b", "把所辨之诚落实于祭前与待人。", "Put sincerity into ritual preparation and dealings with others.",
             "以实际准备检验内心，承担自省而非只求空静。", "Test inward sincerity through preparation and conduct rather than seeking emptiness alone.", 15, 40, 5, 10, 40),
           o("c", "强压哀喜，宣称我已全无情。", "Suppress grief and joy and claim to be beyond feeling.",
             "逞示无情不能替代诚与复性，压抑也带来负担。", "A display of emotional emptiness cannot replace sincerity and burdens the heart.", 0, -25, 20, 15, 0)),
          "李翱复性与澄心的游戏情境；不声称所有情感皆恶，不与韩愈折叠为单纯反佛路线。",
          "A designed case concerning Li Ao's restoration of nature and calming the heart; it does not declare every emotion evil or reduce the route to Han Yu's polemic."),
        p("R13", "诚与静，如何落于日用？", "Sincerity and Stillness in Daily Practice",
          "你在讲席读到阴阳生化与诚的讨论。门人备下图说，盼你把它挂在祭所；可你的心仍被求名牵动。观图与静养，应当怎样相助？",
          "The assembly discusses transformations of yin and yang and sincerity. Pupils prepare a diagram for the ritual room, but your heart is still drawn toward acclaim. How might contemplation and stillness support each other?",
          (o("a", "静养少欲，先使祭前诚心有本。", "Cultivate stillness and simplicity before the offering.",
             "以静养检点欲念，减少外求声名而养诚。", "Examine desires through stillness and nurture sincerity while stepping back from acclaim.", 5, 40, -10, -10, 25),
           o("b", "研读生化之说，再以日用验其诚。", "Study transformation and test sincerity in daily conduct.",
             "图说须与成德相贯，不把解释天地变成陈设而已。", "Join cosmological interpretation to cultivation rather than displaying a diagram alone.", 15, 30, 10, 10, 45),
           o("c", "只请人悬图，便宣称我已得道。", "Hang the diagram and announce that I have attained the Way.",
             "以符号代替工夫，图说本身不会赋予圣德或法力。", "Symbols replace cultivation; the diagram grants neither sagehood nor magical power.", 25, -25, 25, -5, 0)),
          "周敦颐诚、静与生化的匿名义理题；不把后世学统整齐回填其时代，不授予宇宙操控能力。",
          "An anonymous case concerning Zhou Dunyi's sincerity, stillness and transformation; later lineages are not projected backward, and no cosmic powers are granted."),
        p("R14", "仁的体认与持敬的工夫", "Recognizing Humaneness and Maintaining Reverence",
          "讲席讨论仁与敬。有门人偏重体认人与万物的联系，另有人强调整肃心念与求理。祭前的一次怠慢使你看见，讲得明白未必等于行得真切。",
          "The assembly debates humaneness and reverent attention. Some emphasize recognizing connections with others; others stress disciplined attention and inquiry. A lapse before the offering reminds you that clear speech is not the same as sincere conduct.",
          (o("a", "由待人之仁反求祭礼之敬。", "Examine ritual reverence through humane dealings.",
             "以仁的体认检验待人，出资照料并减少隔阂。", "Test the recognition of humaneness through care for others, accepting its expense.", 25, 45, 5, -5, 25),
           o("b", "持敬求理，逐项反省怠慢所由。", "Maintain reverence and inquire into the source of the lapse.",
             "整肃心念并持续问学，工夫更重而非仅守外形。", "Discipline attention through sustained inquiry rather than outward form alone.", 10, 35, -5, 15, 45),
           o("c", "只说天理在我，何须再问待人？", "Claim that principle is mine and ignore my dealings with others.",
             "以天理之名自免省察，不能由此证明仁或敬。", "Invoking principle to avoid examination establishes neither humaneness nor reverence.", 0, -30, 25, -5, 0)),
          "二程之间不同侧重的综合情境；两种正向工夫均非其全部学说，也不赋予持有者道德绝对正确。",
          "A composite dilemma reflecting different Cheng emphases; neither positive practice exhausts a brother's teaching or makes the actor infallible."),
        p("R15", "报本与民胞物与", "Ancestral Origins and Kinship with the World",
          "讲席以气化论天人联系，祭礼却使你先看见自身仍有偏私。有族人问：若只敬自己的祖先，而全然不顾眼前他人的哀苦，如何说民胞物与？",
          "The assembly discusses transformations of qi and the relation of humanity to Heaven. Preparation reveals your remaining partiality. If ancestral reverence ignores the grief of others, how can you speak of kinship with the world?",
          (o("a", "亲习礼以变化气质，先改自身偏私。", "Practice ritual to transform my dispositions and partiality.",
             "气质之性须经工夫变化，反复习礼并非一言悟道。", "Transform dispositions through repeated practice rather than claiming an instant realization.", 10, 35, -10, 15, 45),
           o("b", "敬祖之余，也承担对哀者的照料。", "Join ancestral reverence to care for those who grieve.",
             "把民胞物与落实于照料，报本与待人各有实际责任。", "Put kinship with others into costly care while preserving ancestral duties.", 30, 45, 10, 5, 25),
           o("c", "既都由气化，便不必哀敬或照料。", "Invoke qi to dismiss grief, reverence and care.",
             "以宇宙解释卸去人的工夫，背离礼与变化气质之责。", "Use cosmology to evade cultivation and the duties expressed in ritual.", 0, -30, 10, -5, 0)),
          "张载气化、礼与变化气质的匿名题；不把气解为现代物理物质，不把善行写成神灵施赏。",
          "An anonymous case concerning Zhang Zai's qi, ritual and transformation of dispositions; qi is not reduced to modern physical matter, and good conduct does not cause supernatural rewards."),
        p("R16", "观物不等于预知", "Contemplation Is Not Foreknowledge",
          "有人带来象数推演，请你在祭礼讲席宣布来岁祸福已定。你愿意由观物理解天地，却也知道，说明一种秩序与准确预知每件事并非一回事。",
          "Someone presents a numerical interpretation and asks you to announce next year's fortune at the ritual assembly. Contemplating things may illuminate order, yet explaining a pattern is not the same as foreseeing every event.",
          (o("a", "细读象数，说明所能解释与所不能知。", "Study images and numbers and state the limits of interpretation.",
             "观物成为问学工夫，承认未知可能损及神秘声望。", "Make contemplation a discipline of inquiry while accepting the loss of a prophetic reputation.", 10, 30, -10, 10, 45),
           o("b", "以时序安排习礼，不许必应之诺。", "Use seasonal order in ritual preparation without promising fulfillment.",
             "将对天道运行的理解用于合宜准备，仍不操纵天时。", "Use an understanding of order for fitting preparation without controlling the seasons.", 20, 40, 10, 5, 25),
           o("c", "宣称推演已证明所有未来。", "Declare that the calculation proves the entire future.",
             "以确定预言取悦听众，越过解释的限度；不会生成预知能力。", "Please listeners with certainty that exceeds interpretation; no foreknowledge is created.", 25, -25, 25, -10, 0)),
          "以邵雍象数、观物为素材，祭前讲席为设计情境；不模拟必然准确的占卜或更改天气。",
          "Draws on Shao Yong's images, numbers and contemplation in a designed assembly; no infallible divination or weather changes are simulated."),
        p("R17", "旧注、新义与祭前问学", "Inherited Glosses and New Interpretations",
          "重读《周礼》时，新义与旧注在一处仪节解释上相异。门人盼你只宣布新说胜出，你却要说明，经义怎样回应眼前处境而不成为任意的借口。",
          "A new interpretation of the Rites of Zhou differs from an old gloss concerning a ritual form. Pupils want a declaration of victory, but you must explain how interpretation can respond to circumstances without becoming arbitrary.",
          (o("a", "并核经文与旧注，使新义经得起问难。", "Compare the text and glosses and expose the new reading to criticism.",
             "重新解释仍须经据与论证，不能因名为新学便自免问学。", "New interpretation still requires evidence and argument rather than immunity from criticism.", 10, 30, -10, 10, 45),
           o("b", "据可说明的经义改进这次习礼。", "Use a reasoned interpretation to improve this ritual rehearsal.",
             "把经义用于具体处境，另付准备费用并承担说明责任。", "Apply interpretation to the situation, paying for preparation and accepting the burden of explanation.", 25, 40, 10, 5, 30),
           o("c", "既是我的新义，便无需再核经据。", "My new reading needs no further textual grounds.",
             "以学派名号代替经义，声势不能证明理解。", "A school's name replaces textual understanding; acclaim cannot establish correctness.", 5, -25, 25, -5, 5)),
          "王安石重新释经的义理素材；仅为私人问学与习礼，不执行新法或把全部变法政策宗教化。",
          "Draws on Wang Anshi's reinterpretation of the classics; this is private study and rehearsal, not implementation or religious conversion of the New Policies."),
        p("R18", "人情在礼中何所安？", "How Do Human Feelings Find Form in Ritual?",
          "丧祭讲席上，一篇经义解释得十分整齐，却使哀者无从表达真情。另一篇只谈旷达，又近乎略去礼责。你要如何在经义、人情与礼的分寸之间求义？",
          "At a discussion of mourning, one neat interpretation leaves no room for grief. Another praises freedom from care and nearly abandons ritual duties. How will you examine the relation of textual meaning, human feelings and fitting form?",
          (o("a", "辨经义所指，不以整齐辞句盖过人情。", "Examine the text without letting neat phrases obscure feelings.",
             "经义的理解接受人情与仪节的检验，增加问学负担。", "Test interpretation against feelings and ritual forms, accepting the demands of inquiry.", 15, 30, -5, 10, 45),
           o("b", "因哀者真情简繁合宜，使礼有所安。", "Adjust preparation to give sincere grief a fitting form.",
             "以费用和亲身筹备安顿哀敬，不以放达免去礼责。", "Give grief fitting form through expense and preparation rather than using freedom as an excuse.", 25, 40, 10, -5, 25),
           o("c", "自称旷达，连哀敬与仪节也省去。", "Call myself carefree and set aside grief and ritual duties.",
             "以名士姿态省去承担，不能由此证明经义已明。", "An air of freedom evades responsibility rather than demonstrating understanding.", 0, -25, 20, -15, 0)),
          "苏氏经义、人情与礼义的综合设计，不将此事当作三苏传记，不把蜀地人物全列为一派。",
          "A designed synthesis concerning the Su family's texts, feelings and ritual; it is not a biographical episode or a denomination embracing every Sichuan scholar."),
        p("R19", "察识之后，如何涵养？", "What Follows Moral Recognition?",
          "一位门人自称已察识仁心，祭前遇到烦扰却仍轻慢待人。另一位只求安静，又不愿检点临事所发。识得与养得，究竟怎样相互检验？",
          "A pupil claims to recognize humaneness but treats others impatiently before the offering. Another seeks quiet while refusing to examine responses in actual situations. How can recognition and nourishment test each other?",
          (o("a", "察所发之心，辨一念中有无自欺。", "Examine the arising intention and possible self-deception.",
             "察识不能只成一句自称，须承受辨心与改过的工夫。", "Recognition must be more than a claim and demands examination and correction.", 5, 35, -10, 15, 40),
           o("b", "以日用涵养，使所得见于待人习礼。", "Nourish understanding through daily dealings and ritual.",
             "持续涵养以检验所得，减少纷扰而非逃避实际责任。", "Sustain cultivation to test understanding, reducing distraction without abandoning duties.", 15, 40, 5, -10, 25),
           o("c", "既已识仁，今后行为便无须再问。", "Having recognized humaneness, my conduct needs no scrutiny.",
             "一次体认之名不能免除后续工夫。", "A claim of recognition does not remove the need for continued cultivation.", 0, -30, 25, -5, 0)),
          "胡宏、张栻相关察识与涵养争论的匿名设计；不将湖湘全体定为同一公式或朱学附庸。",
          "An anonymous design concerning Huxiang recognition and nourishment; it does not impose one formula on the entire lineage or reduce it to Zhu Xi's school."),
        p("R22", "成效能否代替义？", "Can Results Replace Rightness?",
          "祭前筹备兼有照料哀者之责。一位门人只计算名声与支出，另一位只空谈义理而不问事情是否真正办成。经义怎样在具体事情中接受检验？",
          "Preparation includes care for mourners. One pupil calculates only reputation and expense; another speaks of principle without asking whether care was delivered. How should moral learning be tested in concrete affairs?",
          (o("a", "据名物与经义查明此礼应尽之责。", "Examine the particulars and textual grounds of the duties.",
             "不以抽象口号代替具体查验，也不唯计一时利得。", "Examine concrete duties instead of relying on slogans or immediate gain alone.", 15, 30, -5, 10, 45),
           o("b", "出资补足照料，使礼义有实际结果。", "Fund the care so that ritual duties produce actual assistance.",
             "事功须受义的检验；资源支出换来承担而非财富即德。", "Achievement must answer to rightness; expense fulfills duties rather than equating wealth with virtue.", 30, 45, 15, 5, 25),
           o("c", "只要赚得声名，便算义利皆得。", "A favorable reputation must prove both virtue and benefit.",
             "把有利结果当成德性的充分证明，削弱求义工夫。", "Treating favorable outcomes as sufficient proof of virtue weakens moral inquiry.", 5, -25, 25, -10, 0)),
          "永嘉义利与具体实践的匿名祭修题；不自动增收、改变商业制度或将胜利当作神证。",
          "An anonymous Yongjia dilemma concerning benefit, rightness and practice; it does not raise income, change trade institutions or treat victory as divine proof."),
        p("R23", "读史之义与眼前祭礼", "Historical Judgment and the Rite Before Me",
          "讲席以往事争论道义与事功，一人只称功业足以证明一切，另一人只赞清谈却不肯承担祭前照料。你愿让史学问难怎样进入自己的工夫？",
          "A historical discussion debates moral purpose and achievement. One participant treats accomplishment as proof of everything; another praises pure discussion while avoiding duties before the offering. How will historical inquiry shape your conduct?",
          (o("a", "辨成败中的道义，不凭结果抹去责任。", "Examine moral responsibility within success and failure.",
             "历史问难须同时看道义与处境，可能损失直截声名。", "Historical judgment must consider purpose and circumstances, even at the cost of an easy reputation.", 10, 35, -10, 10, 45),
           o("b", "将所知之义付诸此次照料与习礼。", "Put the examined duty into care and ritual practice.",
             "行义养气有具体代价，不能只借往事激昂自许。", "Righteous conduct entails costs rather than mere admiration of past achievement.", 30, 45, 10, 5, 25),
           o("c", "我所赞的强盛，当然也就是德性。", "The power I admire must itself establish virtue.",
             "以强盛压倒求义，功业的声势不能免除辨析。", "Power replaces moral examination; impressive achievement does not make inquiry unnecessary.", 20, -30, 30, -5, 0)),
          "陈亮相关历史、道义与事功素材；不使永康与永嘉完全同义，不增加真实战争胜率。",
          "Draws on Chen Liang's history, moral purpose and achievement; Yongkang is not made identical with Yongjia, and no actual combat advantage is granted."),
        p("R24", "会通要不要抹平异说？", "Must Synthesis Erase Disagreement?",
          "经籍整理时，两种注解在求理与发明本心上各有侧重。门人盼把不同处删去，写成一篇毫无疑义的定论。你当如何使会通仍保留问学？",
          "While arranging texts, two commentaries emphasize inquiry into principle and illumination of the heart differently. Pupils want to delete disagreement and produce a settled conclusion. How can synthesis preserve inquiry?",
          (o("a", "校订经籍，明列各说所能与所未明。", "Collate the texts and state each interpretation's limits.",
             "会通需要细读差异，不能以同一结论省去论证。", "Synthesis requires examination of differences rather than an unargued uniform conclusion.", 15, 30, -10, 15, 50),
           o("b", "让居敬与反求本心共同进入习礼。", "Join reverent inquiry and inward examination in ritual.",
             "以实际工夫相互检验，仍承担准备与讲论的费用。", "Test approaches through cultivation while paying for preparation and discussion.", 25, 45, 10, 5, 30),
           o("c", "删去难处，宣布诸家从来没有分歧。", "Delete the difficulties and proclaim that the schools never differed.",
             "表面一致换来声望，却遮蔽了会通所须面对的问题。", "An appearance of unity attracts acclaim while hiding the problems synthesis must address.", 5, -25, 25, -10, 5)),
          "吴澄式经籍与朱陆会通的匿名情境；不视为元初自动形成的统一教会，不修改他派教义。",
          "An anonymous case based on Wu Cheng's textual work and engagement with Zhu and Lu; it is neither an automatic Yuan-wide church nor a change to other schools' doctrines."),
        p("R25", "静养所得，能否不问人？", "Does Quiet Understanding Dispense with Others?",
          "静养时，你觉得纷扰渐息，却也想让众人知道自己已有所得。门人问，内在自得是否可以免去受教与日常待人的检验。",
          "Quiet cultivation seems to settle your distractions, but you wish everyone to know of your attainment. A pupil asks whether personally gained understanding can dispense with teaching and daily conduct.",
          (o("a", "守静养而不急于示人所得。", "Continue quiet cultivation without displaying attainment.",
             "自得不靠旁人喝彩，暂舍声名而减轻纷扰。", "Personally attained understanding does not rely on acclaim; set aside reputation and distraction.", 5, 35, -10, -15, 25),
           o("b", "在日用与受教中检验我所自得。", "Test my understanding in daily conduct and continued learning.",
             "内在体认须接受自身行为的检验，继续问学而非任意。", "Test inward understanding through conduct and continued inquiry rather than personal whim.", 20, 45, 5, 10, 35),
           o("c", "宣称我已自得，所有问难皆可不理。", "Claim attainment and dismiss every question.",
             "以自得之名拒绝检验，声望不能证明真实工夫。", "Refusing examination in the name of attainment replaces cultivation with reputation.", 0, -30, 25, -10, 0)),
          "白沙静养、自得的设计案例；不归并成阳明学，不把片刻静坐写成历史上的立即成圣。",
          "A designed case concerning Baisha's stillness and personal understanding; it is not collapsed into Yangming learning or presented as instant historical sagehood."),
        p("R26", "此处亦能体认天理吗？", "Can Principle Be Recognized Here Too?",
          "祭前有器物待整，也有宾客待迎。一位门人说只有离开这些俗务、长坐无事，才可能体认天理。你却要问动静内外是否真能如此截断。",
          "Vessels require preparation and guests await reception. A pupil insists that principle can be recognized only after abandoning such affairs and sitting apart. Can movement and stillness, inner and outer, be divided so completely?",
          (o("a", "就在整器待人之间反省所发之心。", "Examine my intentions while preparing vessels and receiving guests.",
             "随处体认要求临事省察，日常处境同样有工夫负担。", "Recognition in every situation requires examination amid affairs and carries a real burden.", 10, 45, -5, 15, 35),
           o("b", "并论动静之说，再以此礼相互检验。", "Compare accounts of movement and stillness through this rite.",
             "问学与体认相助，不因处境繁忙便取消经义说明。", "Join study and recognition without treating busy circumstances as an excuse to abandon explanation.", 20, 35, 10, 5, 45),
           o("c", "既称处处天理，我的怠慢也无需改。", "If principle is everywhere, my negligence needs no correction.",
             "把天理之名当作失责的护符，无法替代省察。", "Using principle as protection for negligence cannot replace examination.", 0, -30, 20, -10, 0)),
          "甘泉随处体认的匿名祭修题；不把湛若水视作王门附属，不制造真实天理判决。",
          "An anonymous Ganquan ritual dilemma; Zhan Ruoshui is not reduced to a Wang follower, and no infallible judgment of principle is created."),
        p("R27", "知道恻隐，然后呢？", "What Follows Knowing Compassion?",
          "祭前你已看见一名受委屈者，也知道自己的允诺尚未兑现。门人称赞你已有良知，你却明白，知道该做什么与真实承担不能彼此割裂。",
          "Before the offering, you see someone harmed and remember an unfulfilled promise. Pupils praise your moral knowledge, yet knowing what should be done cannot be separated from actually accepting responsibility.",
          (o("a", "兑现我所知应尽之责，不再推延。", "Fulfill the duty I recognize instead of delaying.",
             "在事上磨炼承担资源与名声代价，不以心善自免行动。", "Cultivation in affairs bears expense and lost standing rather than relying on a good-heart claim.", 30, 45, -10, 10, 30),
           o("b", "检点自欺，使祭前诚意与所行相合。", "Examine self-deception and join intention to conduct.",
             "致良知须持续去蔽，问学与习礼服务于实际工夫。", "Extending moral knowledge requires sustained correction; study and ritual support actual cultivation.", 10, 40, 5, 15, 45),
           o("c", "知道行善已经足够，允诺可以不兑现。", "Knowing goodness is enough; the promise need not be fulfilled.",
             "把知与行截断，以良知之名掩饰自欺。", "Separate knowing from acting and conceal self-deception behind moral knowledge.", 0, -30, 20, -10, 0)),
          "阳明知行、良知与事上磨炼的匿名案例；不以任意欲望等同良知，不生成实际人物的受害状态。",
          "An anonymous Yangming case concerning knowledge, action and cultivation in affairs; desire is not equated with moral knowledge, and no real victim state is created."),
        p("R28", "戒惧是警醒，还是表演？", "Is Vigilance Attention or Performance?",
          "祭前独处时，一个求名的念头使你不安。有门人劝你时时检点，也有人只让你反复说戒惧之辞，仿佛外在紧张便能证明内心真实。",
          "Alone before the offering, a wish for acclaim troubles you. One pupil advises attentive examination; another asks for repeated words of vigilance, as though outward tension proves inward sincerity.",
          (o("a", "于隐微处慎独，诚实辨认求名之念。", "Examine the subtle wish for acclaim in solitude.",
             "戒惧用于不自欺，须承担持续检点的压力。", "Use vigilance against self-deception while accepting the strain of continued attention.", 5, 45, -10, 15, 35),
           o("b", "静养持守，再把所得用于待人习礼。", "Cultivate steady attention and apply it in ritual and dealings.",
             "良知持守与实际行为相检验，安静不等于放弃责任。", "Test maintained moral knowledge through conduct; quiet attention does not abandon responsibility.", 15, 35, 5, -10, 30),
           o("c", "只显出惶恐姿态，便算已有真工夫。", "Display anxiety as proof of real cultivation.",
             "外在戒惧之貌代替慎独，紧张本身不能证明诚意。", "Outward anxiety replaces sincerity; tension alone does not demonstrate honest intention.", 0, -25, 20, 15, 0)),
          "江右王门戒惧、慎独与持守的设计题；不概括所有成员，也不使忠孝成为无限外在牵制。",
          "A designed Jiangyou case concerning vigilance, solitude and moral attention; it does not impose one formula on every member or create unlimited filial coercion."),
        p("R29", "日用之学，谁可来问？", "Who May Inquire into Everyday Learning?",
          "一场会讲之后，有身份卑微的听者问能否从自己的日用生活修己。也有人只想把自得解释成随意而行。尊身与日用成圣，如何不失自省？",
          "After shared teaching, a listener of humble status asks whether daily life can become a path of cultivation. Others wish to interpret personal understanding as following any impulse. How can care for oneself preserve moral examination?",
          (o("a", "使会讲回应日用之问，也要求各人修己。", "Address ordinary questions while requiring personal cultivation.",
             "学习不因身份卑微而失去意义，授业仍须费用与承担。", "Humble status does not make learning meaningless; teaching still requires resources and responsibility.", 25, 45, -10, 5, 35),
           o("b", "尊身养护，却不以便利免去礼责。", "Care for oneself without using convenience to evade duties.",
             "日用工夫包含照顾身体与省察行为，减少耗损并非任性。", "Daily cultivation includes care for the body and examination of conduct; reducing strain is not license for whim.", 15, 35, 5, -15, 25),
           o("c", "凡我觉得自在的，就直接称为道。", "Call whatever feels comfortable the Way.",
             "便利与自得被混为一谈，失去持续修己的要求。", "Comfort is confused with understanding and the need for continued cultivation disappears.", 0, -30, 20, -10, 0)),
          "泰州尊身、日用与会讲的匿名题；不把普通人可学等同现代平等权制，不概括所有王艮后学。",
          "An anonymous Taizhou dilemma concerning care for oneself, daily life and shared teaching; access to cultivation is not equated with modern equal-rights institutions, nor are all followers homogenized."),
        p("R30", "无人知处的一点求名", "A Hidden Wish for Acclaim",
          "你准备在祭前公开认错，却发现心中仍盼众人称赞。若连认错也藏着求名之意，怎样才算迁善改过，而不是又一次表演？",
          "You plan a public acknowledgment of fault before the offering, yet hope to be praised for it. If confession itself conceals a wish for acclaim, how can correction become more than another performance?",
          (o("a", "独处检点微意，记录所当改的真实过失。", "Examine subtle intentions and record the faults to correct.",
             "慎独诚意须在隐微处用力，承受不求赞许的省察。", "Sincerity requires effort in hidden intentions and examination without applause.", 5, 45, -10, 15, 40),
           o("b", "先补过于实际，不让认错代替补过。", "Repair the actual fault before displaying repentance.",
             "迁善落实于修复责任，资源支出不能只换得表演名声。", "Correction repairs responsibilities; expense is directed toward repair rather than display.", 25, 40, 5, 5, 25),
           o("c", "办一场隆重认错，让众人忘记后续责任。", "Stage impressive repentance and avoid further responsibility.",
             "公开姿态掩去微意与补过，声望不能替代持续诚意。", "Public display conceals intentions and evades repair; reputation cannot replace sincerity.", 20, -30, 30, -10, 0)),
          "蕺山慎独、微意与改过的匿名工夫题，不声称出自某次历史认错事件，不将其直接等同天主教告解。",
          "An anonymous Jishan case concerning solitude, intentions and correction; it is not a historical confession episode or a direct equivalent of Catholic confession."),
        p("R31", "讲席的公义与同党的声名", "Public Responsibility and Factional Reputation",
          "会讲后有人提出祭前筹备中的失责，另一人劝你只维护同门声名，不必听外人的问难。尊师与共同讲学，是否也要求反过来检验自己的行为？",
          "After shared teaching, someone questions a neglected ritual duty. Another urges you to defend the school's reputation and dismiss outsiders. Must honoring teachers and shared learning also examine one's own conduct?",
          (o("a", "让问难进入讲席，不因同门而掩过。", "Admit criticism without concealing faults for fellow pupils.",
             "以义匡谏首先接受自身被检验，付出名声与心力代价。", "Public responsibility begins with accepting examination of oneself, at a cost to standing and ease.", 15, 40, -15, 15, 45),
           o("b", "由我补足礼责，使讲学见于躬行。", "Fulfill the neglected duties so teaching appears in conduct.",
             "公共承担须有实际筹备，不能只以讲席声誉为德。", "Responsibility requires preparation rather than treating the assembly's reputation as virtue.", 30, 45, 10, 5, 25),
           o("c", "同党有名，便无需再辨其所行。", "Our faction's reputation makes scrutiny unnecessary.",
             "把政治归属代替义理判断，讲学的工夫因此受损。", "Political belonging replaces moral judgment and undermines cultivation.", 5, -30, 30, -10, 0)),
          "东林讲学与公共责任的匿名情境；不把政治阵营全转成 faith，不执行朝廷派系清洗或NPC惩罚。",
          "An anonymous Donglin case concerning teaching and responsibility; it does not convert a political alliance into a faith or purge factions and NPCs."),
        p("R32", "气化生生与丧祭的哀敬", "Continuing Transformation and Reverence in Mourning",
          "讲席以气化生生说明天地与人的联系。丧祭将近，有人据此劝你不必再哀敬，仿佛理解生化便取消了人所当尽的报本之责。",
          "The assembly discusses the continuing transformations of qi and the relation of humans to the world. Before a mourning rite, someone suggests that understanding transformation removes the need for grief and ancestral duties.",
          (o("a", "细辨气化与人情，求理解而不卸责任。", "Examine transformation and human feelings without evading duty.",
             "解释天地仍须人的判断，问学与承担不能被截断。", "Cosmological understanding requires human judgment and does not sever study from responsibility.", 10, 35, -10, 10, 45),
           o("b", "使知行相资，在丧祭中亲自报本。", "Join knowledge and action through personal ancestral duties.",
             "报本敬祖以实际仪节表达哀敬，工夫不止于论气。", "Express grief and ancestral reverence in actual ritual forms rather than discussion of qi alone.", 25, 45, 10, 5, 30),
           o("c", "只称万物气化，便不哀、不祭、不照料。", "Invoke transformation to abandon mourning, offerings and care.",
             "把气化之说变成卸责之词，不能证明知行相资。", "Using transformation to evade responsibility does not establish mutually supporting knowledge and action.", 0, -30, 20, -10, 0)),
          "船山气化、知行与丧祭的匿名设计；不将气等同现代物质，不把气学标为现代无神论教会。",
          "An anonymous Chuanshan design concerning qi, knowledge, action and mourning; qi is not reduced to modern matter or the school labeled a modern atheist church."),
        p("R33", "六艺须亲身习行", "The Arts Require Personal Practice",
          "讲席已能背诵礼乐射御书数，真正习礼时却只剩纸上的动作。有人劝你让旁人代练，自己只保留熟读的名声。躬行之学应当如何开始？",
          "The assembly recites ritual, music, archery, charioteering, writing and calculation, yet rehearsal remains a sequence on paper. Someone offers to practice for you while you retain the reputation of learning. How will embodied cultivation begin?",
          (o("a", "亲身习行六艺，接受从笨拙开始。", "Practice the arts personally, beginning with my own awkwardness.",
             "习行要求器具、时间与用力，不能由熟背取代。", "Practice demands equipment, time and effort rather than memorized fluency alone.", 30, 45, -5, 15, 40),
           o("b", "以礼乐相助循序演习，也辨书中之义。", "Rehearse ritual and music progressively while examining their meaning.",
             "实践与说明相互检验，给身体与心志合宜节奏。", "Test explanation through practice while cultivating a fitting rhythm of effort.", 20, 35, 15, -5, 30),
           o("c", "请人代习，我只展示熟背之学。", "Let others practice while I display memorized learning.",
             "把知名与习行分离，背诵难以替代亲身成德。", "Separate reputation from practice; recitation cannot substitute for embodied cultivation.", 5, -25, 25, -10, 10)),
          "颜李六艺习行的匿名题；不模拟现代学校产业，不因射御自动增加军事属性、兵种或军会。",
          "An anonymous Yan-Li case concerning practice of the arts; it creates neither a modern school industry nor automatic military attributes, units or orders."),
        p("R34", "考得一个字，是否已明其义？", "Does Establishing a Word Establish Its Moral Meaning?",
          "你在旧注中查得祭器一字的故训，门人称赞此说已足以压倒一切义理讨论。可是合宜祭礼与人之情欲，仍有尚待说明的问题。",
          "You establish an old gloss for the name of a ritual vessel. Pupils claim that this settles every moral question, yet fitting ritual and human feelings still require explanation.",
          (o("a", "校文辨训，明确证据与尚未定处。", "Collate the text and distinguish evidence from uncertainty.",
             "考据须承认论证限度，持续查验而非凭声名定说。", "Acknowledge the limits of philological evidence and continue inquiry rather than relying on reputation.", 15, 35, -10, 15, 50),
           o("b", "以名物明礼，也问仪节如何安顿人情。", "Use particulars to understand ritual and its treatment of feelings.",
             "故训与义理相检验，不以一句定训取消道德判断。", "Test philology and ethics together rather than treating a gloss as the end of judgment.", 30, 45, 10, 5, 30),
           o("c", "有此字训，待人失义也无需再问。", "This gloss makes my conduct beyond moral scrutiny.",
             "把考据成果当作德性的护符，反而舍去求义。", "Use a philological result as protection from examination and abandon moral inquiry.", 5, -25, 25, -5, 10)),
          "乾嘉故训、名物与义理的综合题；不把惠栋、戴震等人的差别抹平，也不将考据写成拒绝一切祭祀。",
          "A composite Qianjia case concerning philology, particulars and ethics; differences among Hui Dong, Dai Zhen and others remain, and textual inquiry does not reject every offering."),
        p("R35", "微言大义应怎样回应此时？", "How Should Subtle Meaning Address the Present?",
          "同读公羊经说，门人对一处褒贬有不同解释。有人催你照搬更晚的宏大主张，另有人又说旧名例足以包办眼前一切责任。时代处境与经义应怎样相辨？",
          "Readers of Gongyang interpretation disagree over a moral judgment. Some urge adoption of sweeping later claims; others say old categories settle every present duty. How should interpretation distinguish textual meaning and circumstances?",
          (o("a", "细辨名例，保留传承中尚有的异说。", "Examine interpretive categories and preserve unresolved disagreement.",
             "微言大义须有经据，不因路线相近便混成一说。", "Subtle interpretation requires textual grounds rather than treating related lineages as identical.", 10, 35, -10, 15, 45),
           o("b", "据经义说明此时的礼责，不夸称万世定论。", "Explain present ritual duties without claiming a final doctrine for every age.",
             "回应处境仍须辨义与说明，不把后学结论提前回填。", "Respond to circumstances through reasoned interpretation without projecting later conclusions backward.", 25, 45, 10, 5, 30),
           o("c", "把所有后来的主张都说成先师早已定下。", "Claim that every later proposal was already settled by the teachers.",
             "借整齐传承取得声势，遮蔽实际分化与经义限度。", "An invented uniform lineage attracts acclaim while concealing divergence and interpretive limits.", 5, -30, 25, -10, 5)),
          "常州今文经学的匿名题，不回填康有为全部后期主张，不执行超出CK3时间线的历史变革。",
          "An anonymous Changzhou New Text case; it does not project every later Kang Youwei proposal backward or implement historical changes beyond CK3's timeline."),
        p("R36", "经世之义也从一场丧祭开始", "Practical Responsibility Begins within a Rite",
          "读史与谈世务时，门人赞你有经世之名；眼前丧祭的照料与费用却仍无人承担。懂得天下之事，能否免去身边所当尽的责任？",
          "Pupils praise your practical learning in discussions of history and worldly affairs, yet care and expenses for a mourning rite remain unmet. Does understanding the world's affairs remove duties close at hand?",
          (o("a", "辑史求义，检验所论是否真能承担。", "Examine history and test whether my arguments accept responsibility.",
             "经世不是只谈成败，须以义与实际处境反求自身。", "Practical learning examines moral purpose and circumstances rather than discussing success alone.", 15, 35, -10, 15, 45),
           o("b", "先把照料与丧祭办实，再言经世。", "Fulfill care and mourning duties before claiming practical learning.",
             "躬行义理承担资源代价，成效仍受仁义检验。", "Fulfill duties through costly action while keeping achievement subject to moral scrutiny.", 35, 45, 15, 5, 30),
           o("c", "有经世声名便足够，具体责任让他人承担。", "My reputation for practical learning is enough; leave duties to others.",
             "综合学说被用作名号，声望不能替代实际承担。", "A designed synthesis becomes merely a label; reputation does not substitute for responsibility.", 10, -30, 30, -10, 0)),
          "明清义理、历史与现实事务的综合设计，不冒称顾黄王同属统一宗派，不实现完整明清历史mod。",
          "A designed synthesis of Ming-Qing ethics, history and affairs; Gu, Huang and Wang are not made a single historical denomination, and no complete Ming-Qing history mod is implemented."),
    )
