"""Negative static-contract checks; actual gameplay requires native acceptance."""

from __future__ import annotations

from dataclasses import replace
from pathlib import Path
import shutil
import tempfile
import unittest
from unittest.mock import patch

from product import SOURCE, spec
import validate_static


class SupermanStaticContractTests(unittest.TestCase):
    def setUp(self) -> None:
        self.temporary = tempfile.TemporaryDirectory(prefix="sxad-static-contract-")
        self.addCleanup(self.temporary.cleanup)
        self.source = Path(self.temporary.name) / "source"
        shutil.copytree(SOURCE, self.source)
        self.product = replace(spec(), source=self.source)

    def validate(self):
        with patch.object(validate_static, "SOURCE", self.source), patch.object(validate_static, "spec", return_value=self.product):
            return validate_static.validate()

    def append(self, relative: str, content: str) -> None:
        path = self.source / relative
        source = path.read_text(encoding="utf-8-sig")
        path.write_text(source + content, encoding="utf-8-sig", newline="\n")

    def test_reviewed_source_is_green(self) -> None:
        report = self.validate()
        self.assertEqual(report["errors"], [])
        self.assertFalse(report["ck3_started"])

    def test_changed_generated_runtime_is_red(self) -> None:
        relative = "common/scripted_effects/sxad_experience_effects.txt"
        self.append(relative, "\n# manually changed generated output\n")
        self.assertIn(f"generated byte parity mismatch: {relative}", self.validate()["errors"])

    def test_acceptance_marker_leak_is_red(self) -> None:
        relative = "common/scripted_effects/sxad_experience_effects.txt"
        self.append(relative, "\nsxadt_injected_effect = {}\n")
        self.assertIn(f"acceptance marker leaked into runtime: {relative}", self.validate()["errors"])

    def test_scripted_effect_count_over_twenty_is_red(self) -> None:
        relative = "common/scripted_effects/sxad_experience_effects.txt"
        self.append(relative, "\n" + "\n".join(f"sxad_unreviewed_{i}_effect = {{}}" for i in range(21)))
        self.assertTrue(any("scripted-effect definition count exceeds 20" in error for error in self.validate()["errors"]))

    def test_duplicate_and_missing_localization_references_are_red(self) -> None:
        relative = "localization/english/sxad_l_english.yml"
        self.append(relative, '\n sxad_unresolved_reference:0 "$sxad_missing_reference$"\n')
        self.assertTrue(any("missing localization reference english" in error for error in self.validate()["errors"]))
        self.append(relative, ' sxad_unresolved_reference:0 "Duplicate"\n')
        self.assertTrue(any("duplicate localization key" in error for error in self.validate()["errors"]))

    def test_malformed_brace_returns_red_report(self) -> None:
        self.append("common/scripted_effects/sxad_experience_effects.txt", "\n}\n")
        report = self.validate()
        self.assertEqual(report["status"], "RED")
        self.assertTrue(any("unmatched closing brace" in error for error in report["errors"]))

    def test_strings_and_comments_do_not_inflate_top_level_count(self) -> None:
        blocks = validate_static.top_level_blocks('sxad_one = { log = "{quoted}" # {comment}\n nested = {} }\n sxad_two = {}\n')
        self.assertEqual([block.key for block in blocks], ["sxad_one", "sxad_two"])


if __name__ == "__main__":
    unittest.main(verbosity=2)
