# -*- coding: utf-8 -*-
"""Machine-authoritative contracts and Glassfire Gaze progression."""

CONTRACTS = (
    {
        "id": 1, "key": "conqueror", "name_zh": "征服者", "name_en": "Conqueror",
        "goal_zh": "赢得战争", "goal_en": "win wars",
        "milestones_zh": ("第一面败旗已经落进火里。", "疆界开始记得你的名字。", "十场胜利，足够让王冠也学会低头。"),
        "milestones_en": ("The first fallen banner enters the flame.", "Borders are beginning to remember your name.", "Ten victories are enough to teach crowns to bow."),
    },
    {
        "id": 2, "key": "weaver", "name_zh": "织网者", "name_en": "Webweaver",
        "goal_zh": "使用牵制", "goal_en": "spend hooks",
        "milestones_zh": ("第一根暗线已经绷紧。", "宫廷里的呼吸开始随你的指尖起伏。", "十根线结成一张网，而网心总是温暖的。"),
        "milestones_en": ("The first hidden thread is taut.", "A court now breathes with your fingertips.", "Ten threads make a web, and its center is always warm."),
    },
    {
        "id": 3, "key": "saint", "name_zh": "圣徒", "name_en": "Saint",
        "goal_zh": "见证直辖伯爵领改宗", "goal_en": "see held counties change faith",
        "milestones_zh": ("第一簇祷声有了新的回音。", "六座祭坛已经替你保存余温。", "十片土地同诵一名，信仰也有了分量。"),
        "milestones_en": ("The first prayer returns with a new echo.", "Six altars now preserve your warmth.", "Ten lands speak one name; even faith has acquired weight."),
    },
    {
        "id": 4, "key": "patriarch", "name_zh": "家主", "name_en": "Patriarch",
        "goal_zh": "迎来子嗣", "goal_en": "welcome children",
        "milestones_zh": ("第一声啼哭替契约添了一行小字。", "血脉已经长出六条温热的枝。", "十枚新名字，足够把一生写成族谱。"),
        "milestones_en": ("A first cry adds fine print to the pact.", "Six warm branches now grow from your bloodline.", "Ten new names are enough to turn one life into a lineage."),
    },
    {
        "id": 5, "key": "steward", "name_zh": "贤王", "name_en": "Wise Ruler",
        "goal_zh": "完成建设", "goal_en": "complete buildings",
        "milestones_zh": ("第一块新石已经压住旧日的尘。", "六处梁柱替你托起了国度。", "十座新建之物，会比赞歌更久地记住你。"),
        "milestones_en": ("The first new stone has pinned down yesterday's dust.", "Six sets of pillars now shoulder your realm.", "Ten works will remember you longer than any hymn."),
    },
    {
        "id": 6, "key": "reveler", "name_zh": "享乐者", "name_en": "Hedonist",
        "goal_zh": "在低压力下度过生辰", "goal_en": "reach birthdays below high stress",
        "milestones_zh": ("第三支生日蜡烛没有被忧愁吹灭。", "六度岁月从容落杯。", "十个轻盈的年头，情感的滋味恰到好处。"),
        "milestones_en": ("A third birthday candle survives sorrow's breath.", "Six years have settled calmly into the cup.", "Ten light years: emotion seasoned to perfection."),
    },
)

MILESTONES = (3, 6, 10)


GAZE_MILESTONES = (
    {
        "xp": 10, "rerolls": 1, "seals": 0,
        "modifiers": (("diplomacy", 1),),
        "growth_zh": "外交 +1", "growth_en": "Diplomacy +1",
        "desc_zh": "第一重火纹睁开。言辞会更容易找到门缝；我也赠你一次重抽，好让垂青显得更合心意。",
        "desc_en": "The first ring of glassfire opens. Words find narrower doors, and I grant one reroll so favor may better suit your taste.",
    },
    {
        "xp": 20, "rerolls": 0, "seals": 1,
        "modifiers": (("martial", 1),),
        "growth_zh": "军事 +1", "growth_en": "Martial +1",
        "desc_zh": "第二重火纹学会衡量锋刃。你获得一枚封印；偶尔免去一道咒痕，会让下一笔典当更香甜。",
        "desc_en": "The second ring learns the measure of a blade. You gain one seal; waiving a curse-mark now and then sweetens the next pawn.",
    },
    {
        "xp": 30, "rerolls": 2, "seals": 0,
        "modifiers": (("stewardship", 1),),
        "growth_zh": "管理 +1", "growth_en": "Stewardship +1",
        "desc_zh": "第三重火纹开始替你数清每一粒余烬。两次重抽归你，旅人——选择越多，签下的欲望便越像出自本心。",
        "desc_en": "The third ring counts every ember for you. Two rerolls are yours, traveler; the more choices offered, the more desire resembles consent.",
    },
    {
        "xp": 40, "rerolls": 0, "seals": 2,
        "modifiers": (("intrigue", 1),),
        "growth_zh": "谋略 +1", "growth_en": "Intrigue +1",
        "desc_zh": "第四重火纹懂得把秘密藏在眨眼之间。两枚封印已经冷却，足够你从容挑选愿意留下的咒痕。",
        "desc_en": "The fourth ring hides secrets between blinks. Two seals have cooled, enough to choose which curse-marks you are willing to keep.",
    },
    {
        "xp": 50, "rerolls": 2, "seals": 1,
        "modifiers": (("learning", 1),),
        "growth_zh": "学识 +1", "growth_en": "Learning +1",
        "desc_zh": "第五重火纹照见契约背面的字。两次重抽与一枚封印，请收好；知识从不使代价消失，只让你看清它。",
        "desc_en": "The fifth ring illuminates the pact's reverse. Keep two rerolls and one seal; knowledge never removes a price, only reveals it.",
    },
    {
        "xp": 60, "rerolls": 1, "seals": 2,
        "modifiers": (("prowess", 2),),
        "growth_zh": "勇武 +2", "growth_en": "Prowess +2",
        "desc_zh": "第六重火纹沿骨骼燃烧，却仍温柔得像拥抱。一次重抽、两枚封印，以及更锋利的躯壳，都是我的垂青。",
        "desc_en": "The sixth ring burns along the bone, gentle as an embrace. One reroll, two seals, and a sharper vessel are all my favor.",
    },
    {
        "xp": 70, "rerolls": 3, "seals": 1,
        "modifiers": (("diplomacy", 1), ("intrigue", 1)),
        "growth_zh": "外交 +1、谋略 +1", "growth_en": "Diplomacy +1, Intrigue +1",
        "desc_zh": "第七重火纹让真话与谎言共享同一种温度。三次重抽和一枚封印，足够把偶然雕成你偏爱的命运。",
        "desc_en": "The seventh ring gives truth and lies the same warmth. Three rerolls and one seal can carve chance into your preferred fate.",
    },
    {
        "xp": 80, "rerolls": 1, "seals": 3,
        "modifiers": (("martial", 1), ("stewardship", 1)),
        "growth_zh": "军事 +1、管理 +1", "growth_en": "Martial +1, Stewardship +1",
        "desc_zh": "第八重火纹已经能替王冠称重。一次重抽、三枚封印；你可以更大胆地伸手，而我会耐心记账。",
        "desc_en": "The eighth ring can weigh a crown. One reroll and three seals let you reach more boldly while I keep patient account.",
    },
    {
        "xp": 90, "rerolls": 4, "seals": 2,
        "modifiers": (("learning", 1), ("prowess", 2)),
        "growth_zh": "学识 +1、勇武 +2", "growth_en": "Learning +1, Prowess +2",
        "desc_zh": "第九重火纹几乎与灵魂重合。四次重抽、两枚封印——终末尚远，你却已学会如何向它索价。",
        "desc_en": "The ninth ring nearly overlaps the soul. Four rerolls and two seals; the end is distant, yet you have learned to name its price.",
    },
    {
        "xp": 100, "rerolls": 3, "seals": 4,
        "modifiers": (("diplomacy", 1), ("martial", 1), ("stewardship", 1),
                      ("intrigue", 1), ("learning", 1), ("prowess", 2)),
        "growth_zh": "五维各 +1、勇武 +2", "growth_en": "All five skills +1, Prowess +2",
        "desc_zh": "第十重火纹闭合为完整的琉焰之视。三次重抽、四枚封印，以及最后一轮成长——旅人，你终于像一件值得珍藏的契物。",
        "desc_en": "The tenth ring closes into the full Glassfire Gaze. Three rerolls, four seals, and one final growth: traveler, you have become a keepsake worth preserving.",
    },
)


# Reviewed release localization consumed by gen_contracts.py.
CONTRACT_LOCALIZATION = {'french': {'contract_ui.collection_prefix': 'Contrats terminés',
            'contract_ui.collection_none': 'aucun',
            'contract_ui.ledger_label': 'Contrat à vie',
            'contract.conqueror.name': 'Conquérant',
            'contract.conqueror.goal': 'remporter des guerres',
            'contract.conqueror.milestone.3': 'La première bannière tombée entre dans la flamme.',
            'contract.conqueror.milestone.6': 'Les frontières commencent à retenir ton nom.',
            'contract.conqueror.milestone.10': "Dix victoires suffisent à apprendre aux couronnes à s'incliner.",
            'contract.weaver.name': 'Tisserand',
            'contract.weaver.goal': 'dépenser des hameçons',
            'contract.weaver.milestone.3': 'Le premier fil caché est tendu.',
            'contract.weaver.milestone.6': 'Une cour respire désormais sous tes doigts.',
            'contract.weaver.milestone.10': 'Dix fils font une toile, et son centre est toujours chaud.',
            'contract.saint.name': 'Saint',
            'contract.saint.goal': 'voir des comtés tenus changer de foi',
            'contract.saint.milestone.3': 'La première prière revient avec un nouvel écho.',
            'contract.saint.milestone.6': 'Six autels conservent désormais ta chaleur.',
            'contract.saint.milestone.10': 'Dix terres prononcent un seul nom ; même la foi a pris du poids.',
            'contract.patriarch.name': 'Patriarche',
            'contract.patriarch.goal': 'accueillir des enfants',
            'contract.patriarch.milestone.3': 'Un premier cri ajoute des lignes en petits caractères au pacte.',
            'contract.patriarch.milestone.6': 'Six branches chaudes poussent désormais de ta lignée.',
            'contract.patriarch.milestone.10': 'Dix nouveaux noms suffisent à transformer une vie en lignée.',
            'contract.steward.name': 'Souverain Sage',
            'contract.steward.goal': 'achever des constructions',
            'contract.steward.milestone.3': "La première pierre neuve a fixé la poussière d'hier.",
            'contract.steward.milestone.6': 'Six jeux de piliers portent désormais ton royaume.',
            'contract.steward.milestone.10': "Dix œuvres se souviendront de toi plus longtemps que n'importe quel "
                                             'hymne.',
            'contract.reveler.name': 'Hédoniste',
            'contract.reveler.goal': 'fêter des anniversaires sans stress élevé',
            'contract.reveler.milestone.3': "Une troisième bougie d'anniversaire survit au souffle du chagrin.",
            'contract.reveler.milestone.6': 'Six années se sont posées calmement dans la coupe.',
            'contract.reveler.milestone.10': "Dix années légères : l'émotion assaisonnée à la perfection.",
            'contract_ui.none': 'Aucun contrat',
            'contract_ui.select_decision': 'Choisis un contrat à vie',
            'contract_ui.select_decision_desc': 'Laisse le Seigneur du Feu de Verre rédiger un objectif progressif '
                                                'pour cette vie.',
            'contract_ui.select_decision_tooltip': "Choisis un contrat de guerre, d'intrigue, de foi, de famille, "
                                                   "d'intendance ou de festivités",
            'contract_ui.select_decision_confirm': 'Laisse-le écrire',
            'contract_ui.event_title': 'Cette vie en gage',
            'contract_ui.event_desc': "Voyageur, le grand livre final est tentant, mais j'aime aussi regarder une "
                                      'flamme choisir son vent. Choisis-en un ; chaque étape ajoutera au poids de '
                                      'cette vie.',
            'contract_ui.clean_desc': 'Voyageur, tes anciennes braises subsistent, mais cette voie ne laisse aucun '
                                      'héritage à dépenser. Bien — arriver au bout les mains vides rend la pesée plus '
                                      'intéressante. Je placerai tout de même la première faveur sur ton compte.',
            'contract_ui.milestone_title': 'Le contrat miroite',
            'contract_ui.milestone_3_ok': 'La première entrée est faite.',
            'contract_ui.milestone_6_ok': "L'encre tiédit.",
            'contract_ui.milestone_10_ok': 'Ce gage est complet.',
            'contract_ui.gaze_title': 'Regard du Feu de Verre : une nouvelle marque',
            'contract_ui.gaze_ok': "J'accepte cette bienveillance tardive.",
            'contract_ui.reroll': 'Dépense une relance pour de nouvelles faveurs',
            'contract_ui.seal': 'Dépense un sceau pour lever cette marque de malédiction',
            'gaze.10': "Le premier anneau du feu de verre s'ouvre. Les mots trouvent des portes plus étroites, et "
                       "j'accorde une relance afin que la faveur convienne mieux à ton goût.",
            'gaze.20': "Le second anneau apprend la mesure d'une lame. Tu gagnes un sceau ; lever une marque de "
                       'malédiction de temps en temps adoucit le prochain gage.',
            'gaze.30': 'Le troisième anneau compte chaque braise pour toi. Deux relances sont tiennes, voyageur ; plus '
                       'les choix offerts sont nombreux, plus le désir ressemble à un consentement.',
            'gaze.40': 'Le quatrième anneau dissimule des secrets entre les clignements. Deux sceaux ont tiédi, assez '
                       'pour choisir quelles marques de malédiction tu es prêt à conserver.',
            'gaze.50': "Le cinquième anneau éclaire l'envers du pacte. Garde deux relances et un sceau ; le savoir ne "
                       'supprime jamais un prix, il ne fait que le révéler.',
            'gaze.60': "Le sixième anneau brûle le long de l'os, doux comme une étreinte. Une relance, deux sceaux et "
                       'un corps plus affûté sont toute ma faveur.',
            'gaze.70': 'Le septième anneau donne aux vérités et aux mensonges la même chaleur. Trois relances et un '
                       'sceau peuvent tailler le hasard selon ton destin préféré.',
            'gaze.80': 'Le huitième anneau sait peser une couronne. Une relance et trois sceaux te permettent de viser '
                       'plus haut tandis que je tiens patiemment les comptes.',
            'gaze.90': "Le neuvième anneau frôle presque l'âme. Quatre relances et deux sceaux ; la fin est lointaine, "
                       'pourtant tu as appris à nommer son prix.',
            'gaze.100': 'Le dixième anneau se referme pour former le Regard du Feu de Verre complet. Trois relances, '
                        'quatre sceaux et une dernière croissance : voyageur, tu es devenu un souvenir qui mérite '
                        "d'être conservé."},
 'german': {'contract_ui.collection_prefix': 'Abgeschlossene Verträge',
            'contract_ui.collection_none': 'keine',
            'contract_ui.ledger_label': 'Lebenslanger Vertrag',
            'contract.conqueror.name': 'Eroberer',
            'contract.conqueror.goal': 'Kriege gewinnen',
            'contract.conqueror.milestone.3': 'Das erste gefallene Banner sinkt in die Flamme.',
            'contract.conqueror.milestone.6': 'Die Grenzen beginnen, sich deinen Namen zu merken.',
            'contract.conqueror.milestone.10': 'Zehn Siege genügen, um Kronen das Neigen zu lehren.',
            'contract.weaver.name': 'Netzweber',
            'contract.weaver.goal': 'Druckmittel einsetzen',
            'contract.weaver.milestone.3': 'Der erste verborgene Faden ist straff gespannt.',
            'contract.weaver.milestone.6': 'Ein Hof atmet nun unter deinen Fingerspitzen.',
            'contract.weaver.milestone.10': 'Zehn Fäden ergeben ein Netz, und sein Zentrum ist stets warm.',
            'contract.saint.name': 'Heiliger',
            'contract.saint.goal': 'gehaltene Grafschaften im Glauben wechseln sehen',
            'contract.saint.milestone.3': 'Das erste Gebet kehrt mit neuem Echo zurück.',
            'contract.saint.milestone.6': 'Sechs Altäre bewahren nun deine Wärme.',
            'contract.saint.milestone.10': 'Zehn Länder sprechen einen Namen; selbst der Glaube hat Gewicht erlangt.',
            'contract.patriarch.name': 'Patriarch',
            'contract.patriarch.goal': 'Kinder willkommen heißen',
            'contract.patriarch.milestone.3': 'Ein erster Schrei fügt dem Pakt das Kleingedruckte hinzu.',
            'contract.patriarch.milestone.6': 'Sechs warme Zweige wachsen nun aus deinem Blut.',
            'contract.patriarch.milestone.10': 'Zehn neue Namen genügen, um ein Leben in eine Linie zu verwandeln.',
            'contract.steward.name': 'Weiser Herrscher',
            'contract.steward.goal': 'Gebäude vollenden',
            'contract.steward.milestone.3': 'Der erste neue Stein hat den Staub von gestern festgenagelt.',
            'contract.steward.milestone.6': 'Sechs Säulenpaare tragen nun dein Reich.',
            'contract.steward.milestone.10': 'Zehn Werke werden dich länger erinnern als jeder Hymnus.',
            'contract.reveler.name': 'Hedonist',
            'contract.reveler.goal': 'Geburtstage ohne hohen Stress erleben',
            'contract.reveler.milestone.3': 'Eine dritte Geburtstagskerze überlebt des Kummers Atem.',
            'contract.reveler.milestone.6': 'Sechs Jahre haben sich ruhig in den Becher gesenkt.',
            'contract.reveler.milestone.10': 'Zehn leichte Jahre: zur Perfektion gereifte Empfindung.',
            'contract_ui.none': 'Kein Vertrag',
            'contract_ui.select_decision': 'Wähle einen Lebensvertrag',
            'contract_ui.select_decision_desc': 'Lass den Glasfeuerlord ein stufenweises Ziel für dieses Leben '
                                                'festlegen.',
            'contract_ui.select_decision_tooltip': 'Wähle einen Kriegs-, Intrigen-, Glaubens-, Familien-, Verwaltungs- '
                                                   'oder Gelagevertrag',
            'contract_ui.select_decision_confirm': 'Lass ihn schreiben',
            'contract_ui.event_title': 'Dieses Leben als Pfand',
            'contract_ui.event_desc': 'Reisender, das letzte Hauptbuch ist verlockend, doch ich beobachte auch gern, '
                                      'wie eine Flamme ihren Wind wählt. Wähle eines; jeder Schritt wird das Gewicht '
                                      'dieses Lebens mehren.',
            'contract_ui.clean_desc': 'Reisender, deine frühere Glut bleibt, doch diese Spur hinterlässt kein '
                                      'verwertbares Erbe. Gut – am Ende mit leeren Händen anzukommen, macht die Wägung '
                                      'reizvoller. Ich werde den ersten Gefallen dennoch auf Rechnung setzen.',
            'contract_ui.milestone_title': 'Der Vertrag glänzt',
            'contract_ui.milestone_3_ok': 'Der erste Eintrag ist gemacht.',
            'contract_ui.milestone_6_ok': 'Die Tinte wird warm.',
            'contract_ui.milestone_10_ok': 'Dieses Pfand ist vollendet.',
            'contract_ui.gaze_title': 'Glasfeuerblick: Ein neues Mal',
            'contract_ui.gaze_ok': 'Ich nehme diese verspätete Güte an.',
            'contract_ui.reroll': 'Gib einen Neuwurf für neue Gefallen aus',
            'contract_ui.seal': 'Gib ein Siegel aus, um dieses Fluchmal zu erlassen',
            'gaze.10': 'Der erste Ring aus Glasfeuer öffnet sich. Worte finden engere Türen, und ich gewähre einen '
                       'Neuwurf, damit der Gefallen besser zu deinem Geschmack passt.',
            'gaze.20': 'Der zweite Ring erlernt das Maß einer Klinge. Du erhältst ein Siegel; ein gelegentliches '
                       'Erlassen eines Fluchmals versüßt das nächste Pfand.',
            'gaze.30': 'Der dritte Ring zählt jede Glut für dich. Zwei Neuwürfe gehören dir, Reisender; je mehr '
                       'Wahlmöglichkeiten geboten werden, desto mehr ähnelt Begehren einer Zustimmung.',
            'gaze.40': 'Der vierte Ring verbirgt Geheimnisse zwischen den Lidern. Zwei Siegel sind erkaltet, genug, um '
                       'zu wählen, welche Fluchmale du zu behalten bereit bist.',
            'gaze.50': 'Der fünfte Ring beleuchtet die Kehrseite des Pakts. Behalte zwei Neuwürfe und ein Siegel; '
                       'Wissen entfernt nie einen Preis, es offenbart ihn nur.',
            'gaze.60': 'Der sechste Ring brennt am Knochen entlang, sanft wie eine Umarmung. Ein Neuwurf, zwei Siegel '
                       'und ein schärferes Gefäß sind meine ganze Gunst.',
            'gaze.70': 'Der siebte Ring gibt Wahrheit und Lügen die gleiche Wärme. Drei Neuwürfe und ein Siegel können '
                       'den Zufall in dein bevorzugtes Schicksal schnitzen.',
            'gaze.80': 'Der achte Ring vermag eine Krone zu wägen. Ein Neuwurf und drei Siegel lassen dich kühner '
                       'zugreifen, während ich geduldig Rechnung führe.',
            'gaze.90': 'Der neunte Ring überschattet beinahe die Seele. Vier Neuwürfe und zwei Siegel; das Ende ist '
                       'fern, doch du hast gelernt, seinen Preis zu benennen.',
            'gaze.100': 'Der zehnte Ring schließt sich zum vollen Glasfeuerblick. Drei Neuwürfe, vier Siegel und ein '
                        'letztes Wachstum: Reisender, du bist ein Andenken geworden, das es zu bewahren lohnt.'},
 'japanese': {'contract.conqueror.name': '征服者',
              'contract.conqueror.goal': '戦争に勝つ',
              'contract.conqueror.milestone.3': '最初の落ちた旗が炎の中に入る。',
              'contract.conqueror.milestone.6': '国境が汝の名を覚え始めている。',
              'contract.conqueror.milestone.10': '十の勝利は王冠を伏せさせるに十分。',
              'contract.weaver.name': '網織師',
              'contract.weaver.goal': 'フックを使用する',
              'contract.weaver.milestone.3': '最初の隠された糸が張り詰めている。',
              'contract.weaver.milestone.6': '宮廷は今や汝の指先で息をしている。',
              'contract.weaver.milestone.10': '十の糸は網を成し、その中心は常に温かい。',
              'contract.saint.name': '聖者',
              'contract.saint.goal': '保持する伯爵領の信仰変化を見る',
              'contract.saint.milestone.3': '最初の祈りが新たな響きを連れて戻る。',
              'contract.saint.milestone.6': '六つの祭壇が今や汝の温もりを保つ。',
              'contract.saint.milestone.10': '十の土地が同じ名を語り、信仰もまた重みを帯びる。',
              'contract.patriarch.name': '家長',
              'contract.patriarch.goal': '子を迎える',
              'contract.patriarch.milestone.3': '最初の産声が契約に細則を加える。',
              'contract.patriarch.milestone.6': '六つの温かい枝が汝の血統から伸びる。',
              'contract.patriarch.milestone.10': '十の新しい名は、一つの命を系譜に変えるに十分。',
              'contract.steward.name': '賢き支配者',
              'contract.steward.goal': '建築を完成させる',
              'contract.steward.milestone.3': '最初の新しい石が昨日の塵を押さえつけた。',
              'contract.steward.milestone.6': '六組の柱が今や汝の領土を支える。',
              'contract.steward.milestone.10': '十の業は如何なる讃歌よりも永く汝を記憶する。',
              'contract.reveler.name': '快楽主義者',
              'contract.reveler.goal': '高ストレス未満で誕生日を迎える',
              'contract.reveler.milestone.3': '三本目の誕生日の蝋燭が悲嘆の息を生き延びる。',
              'contract.reveler.milestone.6': '六年の月日が静かに杯に沈む。',
              'contract.reveler.milestone.10': '十の軽やかな年——感情は完璧に熟成された。',
              'contract_ui.collection_prefix': '完了した契約',
              'contract_ui.collection_none': 'なし',
              'contract_ui.ledger_label': '生涯契約',
              'contract_ui.none': '契約なし',
              'contract_ui.select_decision': '生涯契約を選ぶ',
              'contract_ui.select_decision_desc': '琉焰卿に、今世の増分目標を記してもらおう。',
              'contract_ui.select_decision_tooltip': '戦争・陰謀・信仰・家族・執政・歓宴の契約から一つを選ぶ',
              'contract_ui.select_decision_confirm': '彼に書かせよう',
              'contract_ui.event_title': '質草としての此の世',
              'contract_ui.event_desc': '旅人よ、最終台帳は魅惑的だが、私はまた炎が風を選ぶ様を見守るのも好む。一つ選びなさい。歩むごとに、今生の重みが増すだろう。',
              'contract_ui.clean_desc': '旅人よ、汝の以前の残り火は残るが、この道は使える遺産を残さぬ。よろしい——空手のまま終えることは、計量をもっと興味深いものにする。最初の好意は勘定につけておこう。',
              'contract_ui.milestone_title': '契約が輝く',
              'contract_ui.milestone_3_ok': '最初の記入が為された。',
              'contract_ui.milestone_6_ok': '墨が温み始めている。',
              'contract_ui.milestone_10_ok': 'この質草は完了した。',
              'contract_ui.gaze_title': '琉焰の瞳：新しき刻',
              'contract_ui.gaze_ok': 'この遅れた温情を受け入れよう。',
              'contract_ui.reroll': '新たな好意を得るために再抽選を一つ費やす',
              'contract_ui.seal': 'この呪痕を免除するために封印を一つ費やす',
              'gaze.10': '琉焰の最初の環が開く。言葉は狭き戸を見出し、私はお前の好みに合うよう、再抽選を一つ授けよう。',
              'gaze.20': '第二の環は刃の寸法を学ぶ。お前は封印を一つ得る。呪痕を時折免除すれば、次の質草がより甘くなる。',
              'gaze.30': '第三の環はお前のために全ての残り火を数える。再抽選が二つ授けられよう、旅人よ。選択肢を多く示されるほど、欲望は同意に近づく。',
              'gaze.40': '第四の環は瞬きの間に秘密を匿う。二つの封印が冷め、汝が残したい呪痕を選ぶには足りよう。',
              'gaze.50': '第五の環は契約の裏側を照らす。再抽選二つと封印一つを保つがよい。知識は代価を消すのではなく、晒すのみ。',
              'gaze.60': '第六の環は抱擁のごとく優しく、骨に沿って燃ゆ。再抽選一つ、封印二つ、そして研ぎ澄まされた器、これこそが我が好意の全て。',
              'gaze.70': '第七の環は真と偽に同じ温もりを与える。再抽選三つと封印一つで、汝は運命を好む姿に彫り刻める。',
              'gaze.80': '第八の環は王冠すら量れる。再抽選一つと封印三つで、私が辛抱強く見守る間、汝はより大胆に手を伸ばせる。',
              'gaze.90': '第九の環は魂とほぼ重なる。再抽選四つと封印二つ。終焉は遠いが、汝はその価格を呼ぶ術を学んだ。',
              'gaze.100': '第十の環は閉じて、完全なる琉焰の瞳となる。再抽選三つ、封印四つ、そして最後の成長が一つ。旅人よ、汝は保存するに値する形見となった。'},
 'korean': {'contract_ui.collection_prefix': '완료한 계약',
            'contract_ui.collection_none': '없음',
            'contract_ui.ledger_label': '평생 계약',
            'contract.conqueror.name': '정복자',
            'contract.conqueror.goal': '전쟁에서 승리하기',
            'contract.conqueror.milestone.3': '첫 번째 쓰러진 깃발이 불길 속으로 들어간다.',
            'contract.conqueror.milestone.6': '국경이 이제 당신의 이름을 새기기 시작한다.',
            'contract.conqueror.milestone.10': '열 번의 승리면 왕관을 숙이기에 충분하다.',
            'contract.weaver.name': '거미줄 직조자',
            'contract.weaver.goal': '구실 사용하기',
            'contract.weaver.milestone.3': '첫 번째 숨겨진 실이 팽팽해졌다.',
            'contract.weaver.milestone.6': '이제 궁정이 당신의 손끝으로 숨 쉰다.',
            'contract.weaver.milestone.10': '열 가닥의 실이 그물을 만들고, 그 중심은 언제나 따뜻하다.',
            'contract.saint.name': '성인',
            'contract.saint.goal': '지배 중인 백작령의 신앙 변화 보기',
            'contract.saint.milestone.3': '첫 번째 기도가 새로운 울림을 품고 돌아온다.',
            'contract.saint.milestone.6': '여섯 제단이 이제 당신의 온기를 간직한다.',
            'contract.saint.milestone.10': '열 개의 땅이 하나의 이름을 노래하고, 신앙조차 무게를 얻었다.',
            'contract.patriarch.name': '가부장',
            'contract.patriarch.goal': '자녀 맞이하기',
            'contract.patriarch.milestone.3': '첫 울음에 계약의 세밀한 조항이 더해진다.',
            'contract.patriarch.milestone.6': '여섯 개의 따뜻한 가지가 이제 당신의 혈통에서 자란다.',
            'contract.patriarch.milestone.10': '열 개의 새 이름이면 한 생명을 혈연으로 바꾸기에 충분하다.',
            'contract.steward.name': '현명한 군주',
            'contract.steward.goal': '건물 완공하기',
            'contract.steward.milestone.3': '첫 번째 새 돌이 어제의 먼지를 눌러 고정했다.',
            'contract.steward.milestone.6': '여섯 기둥 세트가 이제 당신의 영역을 떠받친다.',
            'contract.steward.milestone.10': '열 개의 업적이 어떤 찬가보다 오래 당신을 기억할 것이다.',
            'contract.reveler.name': '쾌락주의자',
            'contract.reveler.goal': '높은 스트레스 없이 생일 맞이하기',
            'contract.reveler.milestone.3': '세 번째 생일 초가 슬픔의 숨결을 견뎌낸다.',
            'contract.reveler.milestone.6': '여섯 해가 잔잔하게 잔 속에 가라앉았다.',
            'contract.reveler.milestone.10': '열 개의 가벼운 해: 감정은 완벽하게 숙성되었다.',
            'contract_ui.none': '계약 없음',
            'contract_ui.select_decision': '평생 계약을 선택하십시오',
            'contract_ui.select_decision_desc': '유리불꽃 군주에게 이번 삶의 점진적 목표를 적게 하시게 하십시오.',
            'contract_ui.select_decision_tooltip': '전쟁, 모의, 신앙, 가문, 경영, 혹은 환락 계약 중 하나를 선택하십시오',
            'contract_ui.select_decision_confirm': '그가 적도록 하십시오',
            'contract_ui.event_title': '전당 잡힌 이 삶',
            'contract_ui.event_desc': '나그네여, 마지막 장부는 마음에 듭니다만, 불꽃이 어느 바람을 고르는지 보는 것도 즐기지요. 하나를 고르십시오; 매 단계가 이 삶의 무게를 '
                                      '더할 것입니다.',
            'contract_ui.clean_desc': '나그네여, 옛 잔불은 남아 있으나 이 이력은 쓸 수 있는 유산을 남기지 않습니다. 좋군요—빈손으로 끝에 다다르면 저울질이 더욱 흥미로워집니다. '
                                      '그래도 첫 번째 호의는 외상으로 장부에 올려두겠습니다.',
            'contract_ui.milestone_title': '계약이 빛난다',
            'contract_ui.milestone_3_ok': '첫 항목이 기록되었다.',
            'contract_ui.milestone_6_ok': '잉크가 따뜻해지고 있다.',
            'contract_ui.milestone_10_ok': '이 전당이 완성되었다.',
            'contract_ui.gaze_title': '유리불꽃의 시선: 새로운 주흔',
            'contract_ui.gaze_ok': '이 늦은 호의 감사히 받겠네.',
            'contract_ui.reroll': '새로운 호의를 위해 재추첨을 한 번 사용하십시오',
            'contract_ui.seal': '이 주흔을 면제하려면 인장을 한 개 사용하십시오',
            'gaze.10': '유리불꽃의 첫 번째 고리가 열린다. 말문이 좁아지나, 재추첨을 하나 들여 보내니 호의가 나그네 입맛에 맞을 것이다.',
            'gaze.20': '두 번째 고리가 칼날의 분간을 익힌다. 인장을 하나 얻으리라; 이따금 주흔을 면해 주면 다음 전당이 더 달콤해진다.',
            'gaze.30': '세 번째 고리가 나그네를 위해 모든 잔불을 센다. 재추첨 둘이 그대 것이니, 나그네여; 선택지가 많을수록 욕망이 동의에 더 가까워진다.',
            'gaze.40': '네 번째 고리가 눈짓 사이로 비밀을 감춘다. 식은 인장 둘이 생겼으니, 두고자 하는 주흔을 가려낼 만큼이다.',
            'gaze.50': '다섯 번째 고리가 계약의 이면을 비춘다. 재추첨 두 개와 인장 하나를 지니라; 지식은 값을 없애지 못하나 그 값을 드러낼 뿐이다.',
            'gaze.60': '여섯 번째 고리가 뼈를 따라 탄다, 포옹하듯 부드럽게. 재추첨 하나와 인장 둘, 그리고 더 날카로운 그릇이 내 호의의 전부다.',
            'gaze.70': '일곱 번째 고리가 진실과 거짓에 같은 온기를 준다. 재추첨 셋과 인장 하나로 운명을 그대 뜻대로 깎을 수 있다.',
            'gaze.80': '여덟 번째 고리가 왕관을 저울질한다. 재추첨 하나와 인장 셋으로 대담히 뻗을 수 있으나, 나는 묵묵히 장부를 적는다.',
            'gaze.90': '아홉 번째 고리가 거의 영혼과 겹친다. 재추첨 넷과 인장 둘; 끝은 멀지만 그대는 그 값에 이름을 붙이는 법을 익혔다.',
            'gaze.100': '열 번째 고리가 닫혀 완전한 유리불꽃의 시선이 된다. 재추첨 셋, 인장 넷, 그리고 마지막 성장 하나: 나그네여, 그대는 보존할 가치가 있는 유물이 되었네.'},
 'polish': {'contract_ui.collection_prefix': 'Ukończone kontrakty',
            'contract_ui.collection_none': 'brak',
            'contract_ui.ledger_label': 'Kontrakt życiowy',
            'contract.conqueror.name': 'Zdobywca',
            'contract.conqueror.goal': 'wygrywać wojny',
            'contract.conqueror.milestone.3': 'Pierwszy upadły sztandar trafia w płomień.',
            'contract.conqueror.milestone.6': 'Granice zaczynają pamiętać twe imię.',
            'contract.conqueror.milestone.10': 'Dziesięć zwycięstw wystarczy, by korony nauczyły się schylać.',
            'contract.weaver.name': 'Tkacz Sieci',
            'contract.weaver.goal': 'wydawać haki',
            'contract.weaver.milestone.3': 'Pierwsza ukryta nić jest napięta.',
            'contract.weaver.milestone.6': 'Dwór oddycha teraz twoimi palcami.',
            'contract.weaver.milestone.10': 'Dziesięć nici tworzy sieć, a jej środek zawsze jest ciepły.',
            'contract.saint.name': 'Święty',
            'contract.saint.goal': 'widzieć zmianę wiary w dzierżonych hrabstwach',
            'contract.saint.milestone.3': 'Pierwsza modlitwa wraca z nowym echem.',
            'contract.saint.milestone.6': 'Sześć ołtarzy zachowuje teraz twe ciepło.',
            'contract.saint.milestone.10': 'Dziesięć krain mówi jednym imieniem; nawet wiara nabrała ciężaru.',
            'contract.patriarch.name': 'Patriarcha',
            'contract.patriarch.goal': 'witać dzieci',
            'contract.patriarch.milestone.3': 'Pierwszy krzyk dopisuje drobny druk do paktu.',
            'contract.patriarch.milestone.6': 'Sześć ciepłych gałęzi wyrasta teraz z twego rodu.',
            'contract.patriarch.milestone.10': 'Dziesięć nowych imion wystarczy, by jedno życie przemienić w linię.',
            'contract.steward.name': 'Mądry Władca',
            'contract.steward.goal': 'ukończyć budowle',
            'contract.steward.milestone.3': 'Pierwszy nowy kamień przygwoździł wczorajszy kurz.',
            'contract.steward.milestone.6': 'Sześć rzędów filarów dźwiga teraz twe królestwo.',
            'contract.steward.milestone.10': 'Dziesięć dzieł będzie pamiętać cię dłużej niż jakikolwiek hymn.',
            'contract.reveler.name': 'Hedonista',
            'contract.reveler.goal': 'obchodzić urodziny bez wysokiego stresu',
            'contract.reveler.milestone.3': 'Trzecia świeca urodzinowa przetrwa oddech smutku.',
            'contract.reveler.milestone.6': 'Sześć lat usiadło spokojnie w kielichu.',
            'contract.reveler.milestone.10': 'Dziesięć lekkich lat: emocja doprawiona do perfekcji.',
            'contract_ui.none': 'Brak kontraktu',
            'contract_ui.select_decision': 'Wybierz dożywotni kontrakt',
            'contract_ui.select_decision_desc': 'Niech Władca Szklanego Ognia wyznaczy cel przyrostowy dla tego życia.',
            'contract_ui.select_decision_tooltip': 'Wybierz kontrakt wojny, intrygi, wiary, rodziny, zarządzania lub '
                                                   'uczty',
            'contract_ui.select_decision_confirm': 'Niech go spisze',
            'contract_ui.event_title': 'To życie w zastaw',
            'contract_ui.event_desc': 'Wędrowcze, ostateczny rejestr jest kuszący, lecz z przyjemnością patrzę, jak '
                                      'płomień wybiera swój wiatr. Wybierz jeden; każdy krok doda ciężaru temu życiu.',
            'contract_ui.clean_desc': 'Wędrowcze, twoje dawne żary pozostają, lecz ten ślad nie zostawia dziedzictwa, '
                                      'które można wydać. Dobrze — przybycie na koniec z pustymi rękoma czyni ważenie '
                                      'ciekawszym. Mimo to zaksięguję pierwszą przysługę na poczet.',
            'contract_ui.milestone_title': 'Kontrakt lśni',
            'contract_ui.milestone_3_ok': 'Pierwszy wpis jest dokonany.',
            'contract_ui.milestone_6_ok': 'Atrament się rozgrzewa.',
            'contract_ui.milestone_10_ok': 'Ten zastaw jest kompletny.',
            'contract_ui.gaze_title': 'Spojrzenie Szklanego Ognia: nowe znamię',
            'contract_ui.gaze_ok': 'Przyjmuję tę spóźnioną łaskę.',
            'contract_ui.reroll': 'Wydaj jeden przerzut na nowe przysługi',
            'contract_ui.seal': 'Wydaj jedną pieczęć, by uchylić to znamię klątwy',
            'gaze.10': 'Pierwszy krąg szklanego ognia otwiera się. Słowa znajdują węższe drzwi i ja daję ci jeden '
                       'przerzut, aby przysługa lepiej pasowała do twego gustu.',
            'gaze.20': 'Drugi krąg poznaje miarę ostrza. Zyskujesz jedną pieczęć; uchylenie od czasu do czasu '
                       'znamienia klątwy osładza następny zastaw.',
            'gaze.30': 'Trzeci krąg liczy każdy żar dla ciebie. Dwa przerzuty są twoje, wędrowcze; im więcej wyborów '
                       'zaoferowanych, tym bardziej pożądanie upodabnia się do zgody.',
            'gaze.40': 'Czwarty krąg kryje sekrety między mrugnięciami. Dwie pieczęcie ostygły, wystarczy by wybrać, '
                       'które znamię klątwy zechcesz zatrzymać.',
            'gaze.50': 'Piąty krąg odsłania odwrotną stronę paktu. Zachowaj dwa przerzuty i jedną pieczęć; wiedza '
                       'nigdy nie usuwa ceny, jedynie ją ujawnia.',
            'gaze.60': 'Szósty krąg pali wzdłuż kości, łagodnie jak uścisk. Jeden przerzut, dwie pieczęcie i '
                       'ostrzejsze naczynie to cała moja przysługa.',
            'gaze.70': 'Siódmy krąg daje prawdzie i kłamstwu tę samą temperaturę. Trzy przerzuty i jedna pieczęć mogą '
                       'wyciosać szansę w twój wymarzony los.',
            'gaze.80': 'Ósmy krąg potrafi zważyć koronę. Jeden przerzut i trzy pieczęcie pozwalają ci sięgać śmielej, '
                       'podczas gdy ja prowadzę cierpliwy rejestr.',
            'gaze.90': 'Dziewiąty krąg niemal pokrywa się z duszą. Cztery przerzuty i dwie pieczęcie; koniec jest '
                       'daleki, lecz nauczyłeś się nazywać jego cenę.',
            'gaze.100': 'Dziesiąty krąg zamyka się w pełne Spojrzenie Szklanego Ognia. Trzy przerzuty, cztery '
                        'pieczęcie i jeden ostatni wzrost: wędrowcze, stałeś się pamiątką wartą zachowania.'},
 'russian': {'contract_ui.none': 'Нет договора',
             'contract_ui.select_decision': 'Выбери пожизненный договор',
             'contract_ui.select_decision_desc': 'Позволь Владыке Стеклянного Пламени назначить тебе постепенную цель '
                                                 'на эту жизнь.',
             'contract_ui.select_decision_tooltip': 'Выбери договор о войне, интригах, вере, семье, управлении или '
                                                    'пиршестве',
             'contract_ui.select_decision_confirm': 'Позволь ему написать',
             'contract_ui.event_title': 'Эта жизнь в залоге',
             'contract_ui.event_desc': 'Странник, итоговая запись заманчива, но мне также нравится смотреть, как пламя '
                                       'выбирает свой ветер. Выбирай; каждый шаг прибавит веса этой жизни.',
             'contract_ui.clean_desc': 'Странник, твои прежние угольки остаются, но эта стезя не оставляет '
                                       'наследуемого достояния. Хорошо — прийти к концу с пустыми руками делает '
                                       'взвешивание занятнее. Я всё же положу первую милость на счёт.',
             'contract_ui.milestone_title': 'Договор сверкает',
             'contract_ui.milestone_3_ok': 'Первая запись сделана.',
             'contract_ui.milestone_6_ok': 'Чернила теплеют.',
             'contract_ui.milestone_10_ok': 'Этот заклад завершён.',
             'contract_ui.gaze_title': 'Взор Стеклянного Пламени: новый знак',
             'contract_ui.gaze_ok': 'Я принимаю эту запоздалую милость.',
             'contract_ui.reroll': 'Потрать один переброс ради новых милостей',
             'contract_ui.seal': 'Потрать одну печать, чтобы снять этот знак проклятия',
             'gaze.10': 'Первое кольцо стеклянного пламени раскрывается. Слова находят более узкие двери, и я дарую '
                        'один переброс, чтобы милость лучше пришлась тебе по вкусу.',
             'gaze.20': 'Второе кольцо постигает меру клинка. Ты получаешь одну печать; снять знак проклятия время от '
                        'времени делает следующий заклад слаще.',
             'gaze.30': 'Третье кольцо считает ради тебя каждый уголёк. Два переброса твои, странник; чем больше '
                        'предложено выборов, тем больше желание походит на согласие.',
             'gaze.40': 'Четвёртое кольцо прячет тайны между мгновениями век. Две печати остыли — довольно, чтобы '
                        'выбрать, какие знаки проклятия ты готов оставить.',
             'gaze.50': 'Пятое кольцо озаряет обратную сторону договора. Сохрани два переброса и одну печать; знание '
                        'не отменяет цену, лишь открывает её.',
             'gaze.60': 'Шестое кольцо горит вдоль кости, нежно, как объятие. Один переброс, две печати и более острый '
                        'сосуд — вся моя милость.',
             'gaze.70': 'Седьмое кольцо даёт правде и лжи одинаковое тепло. Три переброса и одна печать могут вырезать '
                        'случай в угоду твоей судьбе.',
             'gaze.80': 'Восьмое кольцо способно взвесить корону. Один переброс и три печати позволят тебе дотянуться '
                        'смелее, пока я терпеливо веду счёт.',
             'gaze.90': 'Девятое кольцо почти смыкается с душой. Четыре переброса и две печати; конец далёк, однако ты '
                        'научился называть его цену.',
             'gaze.100': 'Десятое кольцо замыкается в полный Взор Стеклянного Пламени. Три переброса, четыре печати и '
                         'один последний рост: странник, ты стал реликвией, достойной сохранения.',
             'contract_ui.collection_prefix': 'Завершённые контракты',
             'contract_ui.collection_none': 'нет',
             'contract_ui.ledger_label': 'Контракт за всю жизнь',
             'contract.conqueror.name': 'Завоеватель',
             'contract.conqueror.goal': 'побеждать в войнах',
             'contract.conqueror.milestone.3': 'Первое павшее знамя входит в пламя.',
             'contract.conqueror.milestone.6': 'Границы начинают запоминать твоё имя.',
             'contract.conqueror.milestone.10': 'Десяти побед довольно, чтобы научить короны склоняться.',
             'contract.weaver.name': 'Ткач паутины',
             'contract.weaver.goal': 'расходовать влияние',
             'contract.weaver.milestone.3': 'Первая скрытая нить натянута.',
             'contract.weaver.milestone.6': 'Двор теперь дышит под твоими пальцами.',
             'contract.weaver.milestone.10': 'Десять нитей сплетают паутину, и её центр всегда тёпл.',
             'contract.saint.name': 'Святой',
             'contract.saint.goal': 'видеть, как твои графства меняют веру',
             'contract.saint.milestone.3': 'Первая молитва возвращается с новым эхом.',
             'contract.saint.milestone.6': 'Шесть алтарей теперь хранят твоё тепло.',
             'contract.saint.milestone.10': 'Десять земель произносят одно имя; даже вера обрела вес.',
             'contract.patriarch.name': 'Патриарх',
             'contract.patriarch.goal': 'принимать детей',
             'contract.patriarch.milestone.3': 'Первый крик добавляет к договору мелкий шрифт.',
             'contract.patriarch.milestone.6': 'Шесть тёплых ветвей теперь растут из твоего рода.',
             'contract.patriarch.milestone.10': 'Десяти новых имён довольно, чтобы одна жизнь стала родом.',
             'contract.steward.name': 'Мудрый Правитель',
             'contract.steward.goal': 'завершать строительство',
             'contract.steward.milestone.3': 'Первый новый камень придавил вчерашнюю пыль.',
             'contract.steward.milestone.6': 'Шесть рядов колонн теперь держат твоё королевство.',
             'contract.steward.milestone.10': 'Десять трудов запомнят тебя дольше любого гимна.',
             'contract.reveler.name': 'Гедонист',
             'contract.reveler.goal': 'доживать до дней рождения при низком стрессе',
             'contract.reveler.milestone.3': 'Третья свеча на торте устоит против дыхания печали.',
             'contract.reveler.milestone.6': 'Шесть лет спокойно осели в кубке.',
             'contract.reveler.milestone.10': 'Десять лёгких лет: чувство, доведённое до совершенства.'},
 'spanish': {'contract.conqueror.name': 'Conquistador',
             'contract.conqueror.goal': 'ganar guerras',
             'contract.conqueror.milestone.3': 'El primer estandarte caído entra en la llama.',
             'contract.conqueror.milestone.6': 'Las fronteras empiezan a recordar tu nombre.',
             'contract.conqueror.milestone.10': 'Diez victorias bastan para enseñar a las coronas a inclinarse.',
             'contract.weaver.name': 'Tejedora',
             'contract.weaver.goal': 'gastar anzuelos',
             'contract.weaver.milestone.3': 'El primer hilo oculto está tenso.',
             'contract.weaver.milestone.6': 'Una corte ahora respira con la punta de tus dedos.',
             'contract.weaver.milestone.10': 'Diez hilos forman una tela, y su centro siempre está cálido.',
             'contract.saint.name': 'Santo',
             'contract.saint.goal': 'ver condados cambiar de fe',
             'contract.saint.milestone.3': 'La primera oración vuelve con un eco nuevo.',
             'contract.saint.milestone.6': 'Seis altares custodian ahora tu calor.',
             'contract.saint.milestone.10': 'Diez tierras pronuncian un solo nombre; incluso la fe ha adquirido peso.',
             'contract.patriarch.name': 'Patriarca',
             'contract.patriarch.goal': 'acoger hijos',
             'contract.patriarch.milestone.3': 'Un primer llanto añade letra pequeña al pacto.',
             'contract.patriarch.milestone.6': 'Seis ramas cálidas nacen ahora de tu linaje.',
             'contract.patriarch.milestone.10': 'Diez nombres nuevos bastan para convertir una vida en un linaje.',
             'contract.steward.name': 'Gobernante Sabio',
             'contract.steward.goal': 'completar edificios',
             'contract.steward.milestone.3': 'La primera piedra nueva ha clavado el polvo de ayer.',
             'contract.steward.milestone.6': 'Seis juegos de pilares sostienen ahora tu reino.',
             'contract.steward.milestone.10': 'Diez obras te recordarán más que cualquier himno.',
             'contract.reveler.name': 'Hedonista',
             'contract.reveler.goal': 'alcanzar cumpleaños con bajo estrés',
             'contract.reveler.milestone.3': 'Una tercera vela de cumpleaños sobrevive al aliento de la pena.',
             'contract.reveler.milestone.6': 'Seis años se han asentado con calma en la copa.',
             'contract.reveler.milestone.10': 'Diez años ligeros: la emoción sazonada a la perfección.',
             'contract_ui.none': 'Sin contrato',
             'contract_ui.select_decision': 'Elige un contrato de vida',
             'contract_ui.select_decision_desc': 'Deja que el Señor del Fuego de Cristal fije un objetivo incremental '
                                                 'para esta vida.',
             'contract_ui.select_decision_tooltip': 'Elige un contrato de guerra, intriga, fe, familia, administración '
                                                    'o jolgorio',
             'contract_ui.select_decision_confirm': 'Que lo escriba',
             'contract_ui.event_title': 'Esta vida en prenda',
             'contract_ui.event_desc': 'Viajero, el libro final es tentador, pero también disfruto viendo cómo una '
                                       'llama elige su viento. Escoge uno; cada paso sumará peso a esta vida.',
             'contract_ui.clean_desc': 'Viajero, tus brasas anteriores permanecen, pero esta huella no deja herencia '
                                       'gastable. Bien —llegar al final con las manos vacías hace que el pesaje '
                                       'resulte más interesante. Aun así, anotaré el primer favor en cuenta.',
             'contract_ui.milestone_title': 'El contrato brilla',
             'contract_ui.milestone_3_ok': 'La primera entrada está hecha.',
             'contract_ui.milestone_6_ok': 'La tinta empieza a calentarse.',
             'contract_ui.milestone_10_ok': 'Esta prenda está completa.',
             'contract_ui.gaze_title': 'Mirada del Fuego de Cristal: una nueva marca',
             'contract_ui.gaze_ok': 'Acepto esta amabilidad tardía.',
             'contract_ui.reroll': 'Gasta una nueva tirada por favores nuevos',
             'contract_ui.seal': 'Gasta un sello para anular esta marca de maldición',
             'gaze.10': 'El primer anillo del fuego de cristal se abre. Las palabras encuentran puertas más estrechas, '
                        'y te concedo una nueva tirada para que el favor se adapte mejor a tu gusto.',
             'gaze.20': 'El segundo anillo aprende la medida de una hoja. Obtienes un sello; anular una marca de '
                        'maldición de vez en cuando endulza la próxima prenda.',
             'gaze.30': 'El tercer anillo cuenta cada brasa por ti. Dos nuevas tiradas son tuyas, viajero; cuantas más '
                        'opciones se ofrezcan, más se parece el deseo al consentimiento.',
             'gaze.40': 'El cuarto anillo esconde secretos entre parpadeos. Dos sellos se han enfriado, suficientes '
                        'para elegir qué marcas de maldición estás dispuesto a conservar.',
             'gaze.50': 'El quinto anillo ilumina el reverso del pacto. Conserva dos nuevas tiradas y un sello; el '
                        'conocimiento nunca elimina un precio, solo lo revela.',
             'gaze.60': 'El sexto anillo arde a lo largo del hueso, suave como un abrazo. Una nueva tirada, dos sellos '
                        'y un cuerpo más firme: todo mi favor.',
             'gaze.70': 'El séptimo anillo otorga a la verdad y a la mentira el mismo calor. Tres nuevas tiradas y un '
                        'sello pueden tallar el azar en tu destino preferido.',
             'gaze.80': 'El octavo anillo puede sopesar una corona. Una nueva tirada y tres sellos te permiten llegar '
                        'más lejos mientras yo llevo paciente la cuenta.',
             'gaze.90': 'El noveno anillo casi se solapa con el alma. Cuatro nuevas tiradas y dos sellos; el final '
                        'está lejos, aunque ya has aprendido a nombrar su precio.',
             'gaze.100': 'El décimo anillo se cierra en la Mirada del Fuego de Cristal completa. Tres nuevas tiradas, '
                         'cuatro sellos y un último crecimiento: viajero, te has convertido en una reliquia digna de '
                         'conservarse.',
             'contract_ui.collection_prefix': 'Contratos completados',
             'contract_ui.collection_none': 'ninguno',
             'contract_ui.ledger_label': 'Contrato de por vida'}}
