#!/usr/bin/env python3
"""Source-reviewed annual summary manager interrupt contract."""

from __future__ import annotations

from typing import Final


MANAGER_ANNUAL_SUMMARY_TIMELINE_CONTRACTS: Final[
    dict[str, dict[str, object]]
] = {
    "zg361.1": {
        # Player-liege annual review summary. Its immediate block only copies
        # four already-published grade counts into event-local values, and its
        # sole acknowledgement has no effect. The first-cycle window can
        # inherit the outer B1 bank-ticket names from the publication call
        # stack, while a later cycle can expose the same summary without that
        # already-completed outer tuple. R107 also observed the first summary
        # while the surrounding B1 continuation, B2 PIP and notice-deadline
        # calls were still alive. A later annual summary retained that same
        # extended stack after the bank tuple expired. R118 also exposed the
        # pending-continuation stack after B2/notice expiry while retaining the
        # immutable seed-player scope. R181 observed the same summary after the
        # D+340 calibration watchdog fired; that stack retains the watchdog's
        # exact manager/cycle/case tuple while the older generic ticket has
        # expired. R203 observed the same summary after Central activated,
        # with the exact calibration, PIP, notice, CH-D, compensation and P2C
        # tuples still on the outer call stack. Bind all seven exact observed
        # name sets; the summary itself consumes none of those inherited tuples.
        "date_raw": 53156448,
        "date_policy": "product-observation-window",
        "root_character_id": 29037,
        "character_scopes": {
            "zg361_b1_oversight_ticket_owner": 29037,
            "zg361_b1_reopen_ticket_owner": 29037,
        },
        "optional_character_scopes": {
            "zga_phase2_seed_player": 29037,
            "zg361_b1_ticket_owner": 29037,
            "zg361_b1_calibration_watchdog_owner": 29037,
        },
        "unique_character_scope_excludes": {
            "zg361_b1_reopen_ticket_subject": (29037,),
        },
        "scope_types": {
            name: "value"
            for name in (
                "zg361_b1_oversight_ticket_cycle",
                "zg361_b1_oversight_ticket_case",
                "zg361_b1_oversight_ticket_state",
                "zg361_b1_reopen_ticket_cycle",
                "zg361_b1_reopen_ticket_case",
                "zg361_b1_reopen_ticket_state",
                "zg361_b1_reopen_ticket_object",
                "zg361_b1_reopen_ticket_route",
                "zg361_b1_reopen_ticket_hash",
                "zg361_b1_reopen_ticket_reward_hash",
                "zg361_b1_reopen_ticket_book_version",
                "zg361_n_375",
                "zg361_n_35",
                "zg361_n_325",
                "zg361_n_elim",
            )
        },
        "optional_scope_types": {
            "zg361_b1_ticket_cycle": "value",
            "zg361_b1_ticket_case": "value",
            "zg361_b1_ticket_state": "value",
            "zg361_b1_calibration_watchdog_cycle": "value",
            "zg361_b1_calibration_watchdog_case": "value",
        },
        "saved_scope_name_sets": (
            (
                "zg361_b1_bank_ticket_owner",
                "zg361_b1_bank_ticket_season",
                "zg361_b1_bank_ticket_case",
                "zg361_b1_bank_ticket_state",
                "zg361_b1_ticket_owner",
                "zg361_b1_ticket_cycle",
                "zg361_b1_ticket_case",
                "zg361_b1_ticket_state",
                "zg361_b1_oversight_ticket_owner",
                "zg361_b1_oversight_ticket_cycle",
                "zg361_b1_oversight_ticket_case",
                "zg361_b1_oversight_ticket_state",
                "zg361_b1_reopen_ticket_subject",
                "zg361_b1_reopen_ticket_owner",
                "zg361_b1_reopen_ticket_cycle",
                "zg361_b1_reopen_ticket_case",
                "zg361_b1_reopen_ticket_state",
                "zg361_b1_reopen_ticket_object",
                "zg361_b1_reopen_ticket_route",
                "zg361_b1_reopen_ticket_hash",
                "zg361_b1_reopen_ticket_reward_hash",
                "zg361_b1_reopen_ticket_book_version",
                "zg361_n_375",
                "zg361_n_35",
                "zg361_n_325",
                "zg361_n_elim",
            ),
            (
                "zg361_b1_ticket_owner",
                "zg361_b1_ticket_cycle",
                "zg361_b1_ticket_case",
                "zg361_b1_ticket_state",
                "zg361_b1_oversight_ticket_owner",
                "zg361_b1_oversight_ticket_cycle",
                "zg361_b1_oversight_ticket_case",
                "zg361_b1_oversight_ticket_state",
                "zg361_b1_pending_continue_subject",
                "zg361_b1_pending_continue_owner",
                "zg361_b1_pending_continue_cycle",
                "zg361_b1_pending_continue_case",
                "zg361_b1_pending_continue_state",
                "zg361_b1_reopen_ticket_subject",
                "zg361_b1_reopen_ticket_owner",
                "zg361_b1_reopen_ticket_cycle",
                "zg361_b1_reopen_ticket_case",
                "zg361_b1_reopen_ticket_state",
                "zg361_b1_reopen_ticket_object",
                "zg361_b1_reopen_ticket_route",
                "zg361_b1_reopen_ticket_hash",
                "zg361_b1_reopen_ticket_reward_hash",
                "zg361_b1_reopen_ticket_book_version",
                "zg361_b2_pip_review_candidate",
                "zg361_b2_support_mentor",
                "zg361_b2_pip_deadline_owner",
                "zg361_b2_pip_deadline_subject",
                "zg361_b2_pip_deadline_cycle",
                "zg361_b2_pip_deadline_case",
                "zg361_b2_pip_deadline_state",
                "zg361_notice_deadline_owner",
                "zg361_notice_deadline_subject",
                "zg361_notice_deadline_cycle",
                "zg361_notice_deadline_case",
                "zg361_notice_deadline_state",
                "zg361_n_375",
                "zg361_n_35",
                "zg361_n_325",
                "zg361_n_elim",
            ),
            (
                "zg361_b1_ticket_owner",
                "zg361_b1_ticket_cycle",
                "zg361_b1_ticket_case",
                "zg361_b1_ticket_state",
                "zg361_b1_oversight_ticket_owner",
                "zg361_b1_oversight_ticket_cycle",
                "zg361_b1_oversight_ticket_case",
                "zg361_b1_oversight_ticket_state",
                "zg361_b1_reopen_ticket_subject",
                "zg361_b1_reopen_ticket_owner",
                "zg361_b1_reopen_ticket_cycle",
                "zg361_b1_reopen_ticket_case",
                "zg361_b1_reopen_ticket_state",
                "zg361_b1_reopen_ticket_object",
                "zg361_b1_reopen_ticket_route",
                "zg361_b1_reopen_ticket_hash",
                "zg361_b1_reopen_ticket_reward_hash",
                "zg361_b1_reopen_ticket_book_version",
                "zg361_n_375",
                "zg361_n_35",
                "zg361_n_325",
                "zg361_n_elim",
            ),
            (
                "zg361_b1_bank_ticket_owner",
                "zg361_b1_bank_ticket_season",
                "zg361_b1_bank_ticket_case",
                "zg361_b1_bank_ticket_state",
                "zg361_b1_ticket_owner",
                "zg361_b1_ticket_cycle",
                "zg361_b1_ticket_case",
                "zg361_b1_ticket_state",
                "zg361_b1_oversight_ticket_owner",
                "zg361_b1_oversight_ticket_cycle",
                "zg361_b1_oversight_ticket_case",
                "zg361_b1_oversight_ticket_state",
                "zg361_b1_pending_continue_subject",
                "zg361_b1_pending_continue_owner",
                "zg361_b1_pending_continue_cycle",
                "zg361_b1_pending_continue_case",
                "zg361_b1_pending_continue_state",
                "zg361_b1_reopen_ticket_subject",
                "zg361_b1_reopen_ticket_owner",
                "zg361_b1_reopen_ticket_cycle",
                "zg361_b1_reopen_ticket_case",
                "zg361_b1_reopen_ticket_state",
                "zg361_b1_reopen_ticket_object",
                "zg361_b1_reopen_ticket_route",
                "zg361_b1_reopen_ticket_hash",
                "zg361_b1_reopen_ticket_reward_hash",
                "zg361_b1_reopen_ticket_book_version",
                "zg361_b2_pip_review_candidate",
                "zg361_b2_support_mentor",
                "zg361_b2_pip_deadline_owner",
                "zg361_b2_pip_deadline_subject",
                "zg361_b2_pip_deadline_cycle",
                "zg361_b2_pip_deadline_case",
                "zg361_b2_pip_deadline_state",
                "zg361_notice_deadline_owner",
                "zg361_notice_deadline_subject",
                "zg361_notice_deadline_cycle",
                "zg361_notice_deadline_case",
                "zg361_notice_deadline_state",
                "zg361_n_375",
                "zg361_n_35",
                "zg361_n_325",
                "zg361_n_elim",
            ),
            (
                "zga_phase2_seed_player",
                "zg361_b1_ticket_owner",
                "zg361_b1_ticket_cycle",
                "zg361_b1_ticket_case",
                "zg361_b1_ticket_state",
                "zg361_b1_oversight_ticket_owner",
                "zg361_b1_oversight_ticket_cycle",
                "zg361_b1_oversight_ticket_case",
                "zg361_b1_oversight_ticket_state",
                "zg361_b1_pending_continue_subject",
                "zg361_b1_pending_continue_owner",
                "zg361_b1_pending_continue_cycle",
                "zg361_b1_pending_continue_case",
                "zg361_b1_pending_continue_state",
                "zg361_b1_reopen_ticket_subject",
                "zg361_b1_reopen_ticket_owner",
                "zg361_b1_reopen_ticket_cycle",
                "zg361_b1_reopen_ticket_case",
                "zg361_b1_reopen_ticket_state",
                "zg361_b1_reopen_ticket_object",
                "zg361_b1_reopen_ticket_route",
                "zg361_b1_reopen_ticket_hash",
                "zg361_b1_reopen_ticket_reward_hash",
                "zg361_b1_reopen_ticket_book_version",
                "zg361_n_375",
                "zg361_n_35",
                "zg361_n_325",
                "zg361_n_elim",
            ),
            (
                "zg361_b1_calibration_watchdog_owner",
                "zg361_b1_calibration_watchdog_cycle",
                "zg361_b1_calibration_watchdog_case",
                "zg361_b1_oversight_ticket_owner",
                "zg361_b1_oversight_ticket_cycle",
                "zg361_b1_oversight_ticket_case",
                "zg361_b1_oversight_ticket_state",
                "zg361_b1_reopen_ticket_subject",
                "zg361_b1_reopen_ticket_owner",
                "zg361_b1_reopen_ticket_cycle",
                "zg361_b1_reopen_ticket_case",
                "zg361_b1_reopen_ticket_state",
                "zg361_b1_reopen_ticket_object",
                "zg361_b1_reopen_ticket_route",
                "zg361_b1_reopen_ticket_hash",
                "zg361_b1_reopen_ticket_reward_hash",
                "zg361_b1_reopen_ticket_book_version",
                "zg361_b2_pip_review_candidate",
                "zg361_b2_support_mentor",
                "zg361_b2_pip_deadline_owner",
                "zg361_b2_pip_deadline_subject",
                "zg361_b2_pip_deadline_cycle",
                "zg361_b2_pip_deadline_case",
                "zg361_b2_pip_deadline_state",
                "zg361_n_375",
                "zg361_n_35",
                "zg361_n_325",
                "zg361_n_elim",
                "zg361_notice_deadline_owner",
                "zg361_notice_deadline_subject",
                "zg361_notice_deadline_cycle",
                "zg361_notice_deadline_case",
                "zg361_notice_deadline_state",
            ),
            (
                "zg361_b1_calibration_watchdog_case",
                "zg361_b1_calibration_watchdog_cycle",
                "zg361_b1_calibration_watchdog_owner",
                "zg361_b1_oversight_ticket_case",
                "zg361_b1_oversight_ticket_cycle",
                "zg361_b1_oversight_ticket_owner",
                "zg361_b1_oversight_ticket_state",
                "zg361_b1_reopen_ticket_book_version",
                "zg361_b1_reopen_ticket_case",
                "zg361_b1_reopen_ticket_cycle",
                "zg361_b1_reopen_ticket_hash",
                "zg361_b1_reopen_ticket_object",
                "zg361_b1_reopen_ticket_owner",
                "zg361_b1_reopen_ticket_reward_hash",
                "zg361_b1_reopen_ticket_route",
                "zg361_b1_reopen_ticket_state",
                "zg361_b1_reopen_ticket_subject",
                "zg361_b2_pip_deadline_case",
                "zg361_b2_pip_deadline_cycle",
                "zg361_b2_pip_deadline_owner",
                "zg361_b2_pip_deadline_state",
                "zg361_b2_pip_deadline_subject",
                "zg361_b2_pip_review_candidate",
                "zg361_b2_support_mentor",
                "zg361_ch_d_event_case",
                "zg361_ch_d_event_cycle",
                "zg361_ch_d_event_owner",
                "zg361_ch_d_event_subject",
                "zg361_comp_open_subject",
                "zg361_comp_result_subject_scope",
                "zg361_n_325",
                "zg361_n_35",
                "zg361_n_375",
                "zg361_n_elim",
                "zg361_notice_deadline_case",
                "zg361_notice_deadline_cycle",
                "zg361_notice_deadline_owner",
                "zg361_notice_deadline_state",
                "zg361_notice_deadline_subject",
                "zg361_p2c_summary_case",
                "zg361_p2c_summary_cycle",
                "zg361_p2c_ticket_case",
                "zg361_p2c_ticket_cycle",
                "zg361_p2c_ticket_identity",
                "zg361_p2c_ticket_manager",
                "zg361_p2c_ticket_stage",
            ),
        ),
        "boolean_scopes": (),
        "option_count": 1,
        "selected_option_number": 1,
        "selected_native_option_index": 0,
    },
}

