#include "xar_bridge/ck3_12002_nonwar_mailbox.hpp"

namespace xar::ck3_12002 {

void RegisterNonwarMailboxExecutorsV1(
    ck3_11906::MainThreadQueryInstallEnvironmentV1 &environment,
    const NonwarMailboxExecutorsV1 &executors) noexcept {
#if defined(XAR_CK3_ENABLE_G2_PLAYER_LIFESTYLE_FORMAL_WIRE_PRIVATE_V1)
  environment.permitted_executor_trioquadragintary = executors.lifestyle;
#endif
#if defined(XAR_CK3_ENABLE_G2_PLAYER_CONSTRUCTION_VIEW_PROBE_PRIVATE_V1)
  environment.permitted_executor_duoquadragintary = executors.construction;
#endif
#if defined(XAR_CK3_ENABLE_G2_M5_RANKED_MARRIAGE_PRIVATE_QUERY_V1)
  environment.permitted_executor_octotrigintary = executors.ranked_marriage;
#endif
#if defined(XAR_CK3_ENABLE_G2_M5_ALLIANCE_PROJECTION_PRIVATE_QUERY_V1)
  environment.permitted_executor_octoquadragintary = executors.alliance_projection;
  environment.permitted_executor_octosexagintary = executors.relationship;
#if defined(XAR_CK3_ENABLE_G2_M5_HEIR_MARRIAGE_PRIVATE_ACTION_V1)
  environment.permitted_executor_novemsexagintary = executors.marriage_submit;
#endif
#endif
#if defined(XAR_CK3_ENABLE_G2_COUNCIL_COMPOSITION_STEWARD_CANDIDATES_PRIVATE_PROBE_V1)
  environment.permitted_executor_tritrigintary = executors.council_candidates;
#endif
#if defined(XAR_CK3_ENABLE_G2_COUNCIL_APPLICATION_MAIN_PRIVATE_ROUTE_V1)
  environment.permitted_executor_unquadragintary = executors.council;
#endif
#if defined(XAR_CK3_ENABLE_G2_FACTION_GIFT_MITIGATION_ASYNC_PRIVATE_GLUE_V1)
  environment.permitted_executor_quattuortrigintary = executors.faction_gift;
#endif
#if defined(XAR_CK3_ENABLE_G2_ACTIVE_SCHEME_PRIVATE_CANDIDATE_V1)
  environment.permitted_executor_quinquinquagintary = executors.sway_state;
#endif
#if defined(XAR_CK3_ENABLE_G2_ACTIVE_SCHEME_SWAY_FORMAL_PRIVATE_ACTION_V1)
  environment.permitted_executor_octoquinquagintary = executors.sway_action;
#endif
#if defined(XAR_CK3_ENABLE_G2_REALM_LAW_PAUSED_PRIVATE_QUERY_V1)
  environment.permitted_executor_sexquinquagintary = executors.law_final_terms;
#endif
#if defined(XAR_CK3_ENABLE_G2_REALM_LAW_ENACT_PRIVATE_V1)
  environment.permitted_executor_septentrigintary = executors.law_action;
#endif
#if defined(XAR_CK3_ENABLE_G2_ACTIVITY_FEAST_PLANNER_OPEN_PRIVATE_V1)
  environment.permitted_executor_septenquinquagintary = executors.feast_open;
#endif
#if defined(XAR_CK3_ENABLE_G2_ACTIVITY_STAGE1_OPTION_READ_PRIVATE_V1)
  environment.permitted_executor_novemquinquagintary = executors.feast_options;
#endif
#if defined(XAR_CK3_ENABLE_G2_ACTIVITY_STAGE5_CANSTART_PRIVATE_V1)
  environment.permitted_executor_sexagintary = executors.feast_can_start;
#endif
#if defined(XAR_CK3_ENABLE_G2_ACTIVITY_STAGE5_GOLD_COST_PRIVATE_V1)
  environment.permitted_executor_unsexagintary = executors.feast_gold;
#endif
#if defined(XAR_CK3_ENABLE_G2_ACTIVITY_STAGE5_FEAST_FULL_COST_PRIVATE_V1)
  environment.permitted_executor_duosexagintary = executors.feast_full_costs;
#endif
#if defined(XAR_CK3_ENABLE_G2_ACTIVITY_STAGE2_DESTINATION_PRIVATE_V1)
  environment.permitted_executor_trisexagintary = executors.feast_destination;
  environment.permitted_executor_feast_stage2_confirm12002 = executors.feast_stage2_confirm;
#endif
#if defined(XAR_CK3_ENABLE_G2_ACTIVITY_FEAST_STAGE5_START_PRIVATE_V1)
  environment.permitted_executor_quattuorsexagintary = executors.feast_start;
#endif
#if defined(XAR_CK3_ENABLE_G2_ACTIVITY_FEAST_GUEST_CANDIDATE_PRIVATE_V1)
  environment.permitted_executor_quinsexagintary = executors.feast_guest;
#endif
#if defined(XAR_CK3_ENABLE_G2_ACTIVITY_FEAST_GUEST_RULE_TOGGLE_PRIVATE_V1)
  environment.permitted_executor_sexsexagintary = executors.feast_guest_rules;
#endif
#if defined(XAR_CK3_ENABLE_G2_ACTIVITY_FEAST_GUEST_OPINION_PRIVATE_V1)
  environment.permitted_executor_septensexagintary = executors.feast_guest_opinion;
#endif
#if defined(XAR_CK3_ENABLE_G2_PLAYER_FACTION_ALERTS_PRIVATE_QUERY_V1)
  environment.permitted_executor_factions12002 = executors.factions;
#endif
#if defined(XAR_CK3_ENABLE_G2_M5_WAR_CASH_PRIVATE_QUERY_V1)
  environment.permitted_executor_warcash12002 = executors.warcash;
#endif
#if defined(XAR_CK3_ENABLE_G2_M5_FAMILY_OBLIGATIONS_PRIVATE_QUERY_V1)
  environment.permitted_executor_family_obligations12002 = executors.family_obligations;
#endif
#if defined(XAR_CK3_ENABLE_G2_M5_PREWAR_SOURCES_PRIVATE_QUERY_V1)
  environment.permitted_executor_prewar12002 = executors.prewar;
#endif
#if defined(XAR_CK3_ENABLE_G2_GOVERNMENT_RUNTIME_PRIVATE_QUERY_V1)
  environment.permitted_executor_government12002 = executors.government;
#endif
#if defined(XAR_CK3_ENABLE_G2_PLAYER_RELIGION_CONTEXT_PRIVATE_QUERY_V1)
  environment.permitted_executor_religion12002 = executors.religion;
#endif
#if defined(XAR_CK3_ENABLE_G2_PRISONER_COLLECTION_PRIVATE_QUERY_V1)
  environment.permitted_executor_triquinquagintary = executors.prisoner_collection;
#endif
#if defined(XAR_CK3_ENABLE_G2_PRISONER_RANSOM_ACTION_PRIVATE_V1)
  environment.permitted_executor_quattuorquinquagintary = executors.prisoner_ransom;
#endif
#if defined(XAR_CK3_ENABLE_G2_PLAYER_EPIDEMIC_TREATMENT_PRIVATE_QUERY_V1)
  environment.permitted_executor_epidemic_treatment12002 = executors.epidemic_treatment;
#endif
#if defined(XAR_CK3_ENABLE_G2_PLAYER_EPIDEMIC_RECOVERY_PRIVATE_QUERY_V1)
  environment.permitted_executor_epidemic_recovery12002 = executors.epidemic_recovery;
#endif
#if defined(XAR_CK3_ENABLE_G2_RELIGION_CONVERSION_PRIVATE_QUERY_V1)
  environment.permitted_executor_religion_conversion_reasons12002 = executors.religion_conversion_reasons;
#endif
#if defined(XAR_CK3_ENABLE_G2_ACTIVE_SCHEME_PRIVATE_CANDIDATE_V1)
  environment.permitted_executor_sway_completion_execution12002 = executors.sway_completion_execution;
#endif
#if defined(XAR_CK3_ENABLE_G2_PLAYER_RELIGION_REFORM_CONTEXT_PRIVATE_QUERY_V1)
  environment.permitted_executor_religion_reform12002 = executors.religion_reform;
#endif
#if defined(XAR_CK3_ENABLE_G2_PLAYER_RELIGION_DOCTRINE_CATALOGUE_PRIVATE_QUERY_V1)
  environment.permitted_executor_religion_doctrine_catalogue12002 = executors.religion_doctrine_catalogue;
#endif
#if defined(XAR_CK3_ENABLE_G2_RELIGION_CONVERSION_PRIVATE_QUERY_V1)
  environment.permitted_executor_religion_conversion_outcome12002 = executors.religion_conversion_outcome;
#endif
#if defined(XAR_CK3_ENABLE_G2_PLAYER_RELIGION_NUMERIC_SPECIAL_PARAMETERS_PRIVATE_QUERY_V1)
  environment.permitted_executor_religion_numeric_special_parameters12002 = executors.religion_numeric_special_parameters;
#endif
#if defined(XAR_CK3_ENABLE_G2_ACTIVE_SCHEME_PRIVATE_CANDIDATE_V1)
  environment.permitted_executor_sway_completion_termination12002 = executors.sway_completion_termination;
#endif
#if defined(XAR_CK3_ENABLE_G2_PLAYER_RELIGION_PERSONAL_PARAMETERS_PRIVATE_QUERY_V1)
  environment.permitted_executor_religion_personal_parameters12002 = executors.religion_personal_parameters;
#endif
#if defined(XAR_CK3_ENABLE_G2_ACTIVE_SCHEME_PRIVATE_CANDIDATE_V1)
  environment.permitted_executor_sway_completion_invalidation_reason12002 = executors.sway_completion_invalidation_reason;
#endif
#if defined(XAR_CK3_ENABLE_G2_PLAYER_RELIGION_DRAFT_GROUPS_PRIVATE_QUERY_V1)
  environment.permitted_executor_religion_draft_groups12002 = executors.religion_draft_groups;
#endif
#if defined(XAR_CK3_ENABLE_G2_PLAYER_RELIGION_DRAFT_DOCTRINE_CHOICES_PRIVATE_QUERY_V1)
  environment.permitted_executor_religion_draft_doctrine_choices12002 = executors.religion_draft_doctrine_choices;
#endif
#if defined(XAR_CK3_ENABLE_G2_PLAYER_RELIGION_DRAFT_TENET_CHOICES_PRIVATE_QUERY_V1)
  environment.permitted_executor_religion_draft_tenet_choices12002 = executors.religion_draft_tenet_choices;
#endif
#if defined(XAR_CK3_ENABLE_G2_PLAYER_RELIGION_DRAFT_RESOURCE_COSTS_PRIVATE_QUERY_V1)
  environment.permitted_executor_religion_draft_resource_costs12002 = executors.religion_draft_resource_costs;
#endif
#if defined(XAR_CK3_ENABLE_G2_PLAYER_RELIGION_AI_REFORM_INPUTS_PRIVATE_QUERY_V1)
  environment.permitted_executor_religion_ai_reform_inputs12002 = executors.religion_ai_reform_inputs;
#endif
  (void)environment;
  (void)executors;
#if defined(XAR_CK3_ENABLE_G2_PLAYER_RITE_GOVERNANCE_PRIVATE_QUERY_V1)
  environment.permitted_executor_rite_governance12002 = executors.rite_governance;
#endif
#if defined(XAR_CK3_ENABLE_G2_PLAYER_CLERGY_APPOINTMENT_PRIVATE_QUERY_V1)
  environment.permitted_executor_clergy12002 = executors.clergy;
#endif
#if defined(XAR_CK3_ENABLE_G2_RELIGION_CONVERSION_PRIVATE_QUERY_V1)
  environment.permitted_executor_religion_conversion12002 = executors.religion_conversion;
#endif
#if defined(XAR_CK3_ENABLE_G2_PLAYER_RELIGION_DOCTRINES_PRIVATE_QUERY_V1)
  environment.permitted_executor_religion_doctrines12002 = executors.religion_doctrines;
#endif
#if defined(XAR_CK3_ENABLE_G2_PLAYER_RITE_MEMBERS_PRIVATE_QUERY_V1)
  environment.permitted_executor_rite_members12002 = executors.rite_members;
#endif
#if defined(XAR_CK3_ENABLE_G2_RELIGION_CONVERSION_PRIVATE_QUERY_V1)
  environment.permitted_executor_religion_conversion_choices12002 = executors.religion_conversion_choices;
#endif
#if defined(XAR_CK3_ENABLE_G2_RELIGION_CONVERSION_PRIVATE_QUERY_V1)
  environment.permitted_executor_religion_conversion_inputs12002 = executors.religion_conversion_inputs;
#endif
#if defined(XAR_CK3_ENABLE_G2_ACTIVE_SCHEME_PRIVATE_CANDIDATE_V1)
  environment.permitted_executor_sway_completion12002 = executors.sway_completion;
#endif
#if defined(XAR_CK3_ENABLE_G2_PLAYER_RELIGION_HOSTILITY_PRIVATE_QUERY_V1)
  environment.permitted_executor_religion_hostility12002 = executors.religion_hostility;
#endif
#if defined(XAR_CK3_ENABLE_G2_PLAYER_RELIGION_DOCTRINE_KNOWLEDGE_PRIVATE_QUERY_V1)
  environment.permitted_executor_religion_doctrine_knowledge12002 = executors.religion_doctrine_knowledge;
#endif
#if defined(XAR_CK3_ENABLE_G2_PLAYER_RELIGION_TENETS_PRIVATE_QUERY_V1)
  environment.permitted_executor_religion_tenets12002 = executors.religion_tenets;
#endif
}

} // namespace xar::ck3_12002
