"""Project-owned promotional-video presets."""

from .zhongguo_361_phase2 import (
    CORE_PROJECT_CONFIG_BLOCKERS,
    PHASE2_CHAPTER_CONTRACT,
    PHASE2_PROMO_CAPTURE_CONTRACT_VERSION,
    PHASE2_PROMO_CAPTURE_MODE,
    PHASE2_PROMO_CAPTURE_PRODUCER_ID,
    PHASE2_PROMO_CAPTURE_SPAN_MAP,
    PHASE2_PROMO_CLEAN_SPAN_IDS,
    PHASE2_POLICY,
    CaptureRequirements,
    HistoricalSubject,
    Phase2CaptureCandidate,
    Phase2PresetError,
    Phase2PromoPolicy,
    build_narration_request,
    load_phase2_capture_candidate,
    load_phase2_project_config,
    phase2_capture_requirements,
    validate_phase2_project_config,
    validate_rendered_duration,
)

__all__ = [
    "CORE_PROJECT_CONFIG_BLOCKERS",
    "PHASE2_CHAPTER_CONTRACT",
    "PHASE2_PROMO_CAPTURE_CONTRACT_VERSION",
    "PHASE2_PROMO_CAPTURE_MODE",
    "PHASE2_PROMO_CAPTURE_PRODUCER_ID",
    "PHASE2_PROMO_CAPTURE_SPAN_MAP",
    "PHASE2_PROMO_CLEAN_SPAN_IDS",
    "PHASE2_POLICY",
    "CaptureRequirements",
    "HistoricalSubject",
    "Phase2CaptureCandidate",
    "Phase2PresetError",
    "Phase2PromoPolicy",
    "build_narration_request",
    "load_phase2_capture_candidate",
    "load_phase2_project_config",
    "phase2_capture_requirements",
    "validate_phase2_project_config",
    "validate_rendered_duration",
]
